### ISSUE TITLE
Calling continueAsNew from orchestration catch block does not restart orchestration

### ISSUE THREAD

**Issue by teresahoes** [Azure/azure-functions-durable-js#101]
**Describe the bug**
I have a try/catch statement in the orchestrator - under certain circumstances i want to restart the orchestration based on the type of error that happens.  In the catch block i call an activity to email the event and then call 
context.df.continueAsNew(<myinputvalue>);  

however, in the history for the orchestration - i see the email event being called and then the orchestration completes. My understanding is the continueAsNew should wipe the history and start over?

**Investigative information**

- Durable Functions extension version: latest
- durable-functions npm module version: 1.2.2
- Language (JavaScript/TypeScript) and version: typescript
- Node.js version: 8.9.11

***If deployed to Azure App Service***

- Timeframe issue observed: 3:14pm PST
- Function App name: azrfnsfunc
- Function name(s): orchestration_process_form
- Region: north central us
- Orchestration instance ID(s): dee41e50-caa4-11e9-a8bd-fdb675fc7403

**To Reproduce**

call context.df.continueAsNew in an orchestrators catch block

**Expected behavior**
orchestration would start over from the beginning

**Actual behavior**
orchestration completes 'successfully'

**Comment by ConnorMcMahon** [comment]
It is quite possible that this is actually just the behavior of #57 and #81 manifesting. Is continueAsNew() working for you outside of a catch block?

**Comment by ConnorMcMahon** [comment]
The good news is that a fix is ready, and should be out in our next release (expect in the next week).

**Comment by davidmrdavid** [comment]
Hi @PCR-AmitRajput,

I believe this _should_ be fixed already, although this precise issue pre-dates me as the SDK owner.

To answer your question, throwing an exception after calling `ContinueAsNew` isn't exactly well-defined behavior, so the answer here is that we can't be sure the framework will work if you do that, although we try to ensure that it does.

In general, if you're calling `ContinueAsNew`, the exception is that the orchestrator returns _basically_ immediately after. After all, any Durable APIs after a `ContinueAsNew` will / should be ignored. This isn't something we can fully enforce given the flexibility of the programming model, so here we need end-user help in making sure their orchestrator does not do any "real" work after a `ContinueAsNew` call.

Hope that makes sense! Thanks!
