### ISSUE TITLE
Options for conditional callActivityWithRetry

### ISSUE THREAD

**Issue by kepikoi** [Azure/azure-functions-durable-js#103]
https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-error-handling states a `Handle` can be specified in a `RetryOptions` instance to determine whether a function should be retried. As of now  (1.2.4) no such setter is available. 

As a workaround attempt, when running this in the orchestrator
```
try {
        return  yield context.df.callActivityWithRetry("flaky-activity", retryOptions);
} catch (e) {
        // retry on TimeoutError, throw otherwise
        if (!(e instanceof TimeoutError)) {
            throw e;
        }
    }
```
...the catch block currently does not trigger on a e.g. SyntaxError thrown by `flaky-activity` resulting in wasted CPU cycles on retries.

Is there currently any solution to retry an activity conditionally?

**Comment by kepikoi** [comment]
Can we please get an update on this? Quite some time has passed and I still cannot fathom how to use RetryOptions effectively

**Comment by cgillum** [comment]
I don't believe our JS SDK supports this currently, so it would need to be added.

FYI @davidmrdavid

**Comment by davidmrdavid** [comment]
Hi @kepikoi!

Sorry we kept you waiting. I'll have to do some investigating here, to give an estimate of how long this would take to implement. I'll give this a look tomorrow and on Friday and get back to you on this. Expect an update from me!

⚡ ⚡

**Comment by davidmrdavid** [comment]
Quick update:
I gave this a quick look today and did the naive approach of adding the `handle` field, attaching an anonymous function to it, and wishing for the best. Unfortunately, that did not work out of the box. My current understanding is that the `durable-extension`, which ultimately coordinates the Durable Functions logic, does not currently support out-of-process PLs (like JavaScript) sending foreign code as an error handle, so it simply fails. 

We're still discussing this internally, we're trying to figure out a clean solution to this, but it may require changes beyond this codebase. I'll be back with updates!

**Comment by APIWT** [comment]
@davidmrdavid Darn, I had the exact same naive idea but I am happy I found this thread before I sunk too much time in trying it. Do you think this will be addressed soon?

**Comment by davidmrdavid** [comment]
Hi @APIWT ! Sorry for the late response. Since this requires some big changes to `durable-extension`, and is not supported in JavaScript either, we aren't prioritizing this at this moment because we're focused on bringing Durable Python to GA. Immediately after that, which should be happening soon, I'll have more free time to dive into this :) . At the moment though, I can't give you an estimate but it's a priority of mine to give Python and JavaScript as many features as our C# offering, so I'll push to work on it asap!

⚡ ⚡

**Comment by hossam-nasr** [comment]
Closing this in favor of #329
