### ISSUE TITLE
package.json dependency on npm

### ISSUE THREAD

**Issue by DeneshPohar** [Azure/azure-functions-durable-js#106]
See package.json: https://github.com/Azure/azure-functions-durable-js/blob/1363385fcf6f39e092031ab7dfb2cb4fb8896afb/package.json#L36.  This is a `dependency` on `npm`.  This means that packages that consume this library end up with the `npm` dependency as well.

**Investigative information**

- Durable Functions extension version: 1.8.3
- durable-functions npm module version: 1.3.0
- Language (JavaScript/TypeScript) and version: TypeScript 3.6.3
- Node.js version: v10.14.1

***If deployed to Azure App Service***

n/a

**To Reproduce**

1. Create a package that depends on `durable-functions` v1.3.0.
2. Run `npm install`
3. Look at `package-lock.json` dependencies

**Expected behavior**
Compare with `durable-functions` v1.2.2 (for example)

**Actual behavior**
`npm` and its dependencies are bloating the app dependencies.

**Additional context**

- Looks like this was introduced in #102

**Comment by ConnorMcMahon** [comment]
Thanks for catching this, will address this as a part of 1.3.1
