### ISSUE TITLE
waitForExternalEvent not firing off as intended

### ISSUE THREAD

**Issue by KieranDaviesV** [Azure/azure-functions-durable-js#111]
**Describe the bug**
waitForExternalEvent doesn't run anything after it, maybe I'm doing something wrong? 
At first it was in a two deep orchestrator which I thought might be the issue but even in my main orchestrator it fires nothing after it. I get the a 202 successfully that a RaiseEvent was received with the name i gave it, and previous logs appear.

I am using a http request to re-trigger the durable. Basically following this blog:

https://dev.to/azure/durable-functions-application-patterns-13p2

**Investigative information**

- Durable Functions extension version: 1.7.1
- durable-functions npm module version: 1.2 - then updated to 1.3
- Language (JavaScript/TypeScript) and version: typescript 3.3.1
- Node.js version: 8.11.3

**To Reproduce**

1. Run the waitForExternal
2.  use instanceId to run the http request so it knows what instance to restart
3. Re-runs all the logs and ends, nothing after words

> While not required, providing your orchestrator's source code in anonymized form is often very helpful when investigating unexpected orchestrator behavior.

**Expected behavior**
Stop and wait then run the code afterwards

**Actual behavior**
Stops and waits doesn't run any code afterwards - but when it was in the two deep orchestrator it did run the code after the orchestrator returned but didn't return any results.

**Additional context**

- Development environment (ex. Visual Studio) Visual studio on local machine

**Comment by davidmrdavid** [comment]
Hi @KieranDaviesV.

I was doing some backlog cleaning and realized we missed this thread when it was first posted. My apologies.
If this issue is still occurring, please let us know, provide a reproducer if possible, and we can kickstart and investigation. Thank you.
