### ISSUE TITLE
Source code about "checkpointing execution history into storage tables"

### ISSUE THREAD

**Issue by hazelnutsgz** [Azure/azure-functions-durable-js#112]
The documentation mentioned `It does so by using storage queues to drive function invocation and by periodically checkpointing execution history into storage tables`. When checking the source code of `azure-functions-durable-js`, no clues have been found. So I want to know where I could find the implementation of "periodically checkpointing execution history into storage tables", I found the suspicious code in another C# repo,  https://github.com/Azure/durabletask/blob/master/src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs#L334

Looking forward to your reply, thanks!

**Comment by cgillum** [comment]
Close, the actual update of execution history happens here: https://github.com/Azure/durabletask/blob/0a3fdfa35834925f2a970e12f4c77a80d1a51927/src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs#L874

Let us know if you have other questions.

**Comment by hazelnutsgz** [comment]
Many thanks, you helped a lot!
