### ISSUE TITLE
Add support for node 12

### ISSUE THREAD

**Issue by webuniverseio** [Azure/azure-functions-durable-js#116]
At the moment if you launch `func start` with node 12.13.0 installed you get following message:

```
Incompatible Node.js version. The version you are using is v12.13.0, but the runtime requires an LTS-covered major version (ex: 8.11.1 or 10.14.1).
```

v12.13.0 is an LTS version see https://nodejs.org/en/download/

**Investigative information**

- Durable Functions extension version:  2.0
- durable-functions npm module version: 1.3.0
- Language (JavaScript/TypeScript) and version: javascript
- Node.js version: 12.13.0

**To Reproduce**

1. Have node v12.13.0 installed
2. Launch function app as `func start`
3. See error

**Expected behavior**
No error is expected and launch of func start should be successful, just like for node 8 or 10

**Comment by ConnorMcMahon** [comment]
This work is already being tracked here: https://github.com/Azure/azure-functions-nodejs-worker/issues/200.
