### ISSUE TITLE
callHttp fails to make HTTP call

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-durable-js#119]
**Describe the bug**
`context.df.callHttp` doesn't work.

**Investigative information**

- Durable Functions extension version: 2.0.0
- durable-functions npm module version: 1.3.1
- Language (JavaScript/TypeScript) and version: JS
- Node.js version: 10.16.3

**To Reproduce**

1. Clone this repo: https://github.com/anthonychu/test-durable-js
1. ```bash
    npm i
    func extensions install
    cp local.settings.SAMPLE.json local.settings.json
    # Add storage connection string to local.settings.json
    func start
    ```
1. Call `http://localhost:7071/api/orchestrators/DurableFunctionsOrchestratorJS` to start the orchestrator that makes an http call.
1. Get the `statusQueryGetUri` in the response and use it to check the status. It should show an error:
    ```json
    {
        "name":"DurableFunctionsOrchestratorJS","instanceId":"d38d33aea86342c28a27b571def7e720",
        "runtimeStatus":"Failed",
        "input":null,
        "customStatus":null,
        "output":"Unexpected token while deserializing object: PropertyName. Path 'actions[0][0].actionType', line 12, position 21.",
        "createdTime":"2019-11-17T06:54:36Z",
        "lastUpdatedTime":"2019-11-17T06:54:37Z"
    }
    ```

@ConnorMcMahon @cgillum

**Comment by anthonychu** [comment]
Turns out this is due to a mismatch in signatures between [DurableOrchestrationContext.callHttp](https://github.com/Azure/azure-functions-durable-js/blob/94f1fb34035b251e8b7981186a0231bcd79760db/src/durableorchestrationcontext.ts#L133) and the implementation in [Orchestrator.callHttp](https://github.com/Azure/azure-functions-durable-js/blob/94f1fb34035b251e8b7981186a0231bcd79760db/src/orchestrator.ts#L347-L353). I was going by the intellisense so I passed a `DurableHttpRequest` which caused the failure:

![image](https://user-images.githubusercontent.com/3982077/69887854-e5a23600-129d-11ea-8f7c-f12e2cfe3760.png)

Updating the call to pass the correct arguments works:

```js
const response = yield context.df.callHttp(
    'GET', 'https://api.github.com/users/anthonychu/events');
```

**Comment by antempus** [comment]
Oh, this is awesome, look forward to using this soon!
