### ISSUE TITLE
Improve JS orchestration client function experience.

### ISSUE THREAD

**Issue by kashimiz** [Azure/azure-functions-durable-js#12]
Currently, the recommended way to write an orchestration client "starter" function in JavaScript is to bind OrchestrationClient as an output binding, construct an object matching the structure of OrchestrationStartArgs within the function, and set the OrchestrationClient binding equal to the object.

While this approach successfully starts orchestrations, it has several disadvantages compared to the C# experience, such as:

- orchestrationIds must be generated by the starter function, not the extension
- although the instance management endpoints are still available, there is no way to generate the URIs and return them as JSON
- more

This is less than optimal.

**Comment by darnmason** [comment]
I'm really struggling with documentation here, I was under the impression that functions v2 were in full release now and Durable Functions were fully supported in JS.

I'd like to call an orchestration synchronously, but there doesn't seem to be any way to do this with JS? The documentation only contains a C# example: https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-instance-management#wait-for-orchestration-completion

Is the only option to make the client poll for a result?

**Comment by kashimiz** [comment]
Sorry for the confusion, @darnmason ! Here's the status of the various components:

- Functions V2 Runtime: GA (as of Ignite 2018)
- Durable Functions .NET (C#/F#): GA (as of Ignite 2018)
- Durable Functions JS: Public Preview, expected to GA by the end of 2018.

Most places in our docs have a note that calls out whether a Durable Functions feature is supported in JS, but looks like we missed a few.

Presently the only option in JS is, as you said, to make the caller of the client function poll the status endpoint for a result. As part of the work to bring Durable Functions JS to GA, the OrchestrationClient API is being ported over, which should provide an experience like that of C#.

**Comment by darnmason** [comment]
I just saw that tasty PR you have open, looking good!
