### ISSUE TITLE
context.df.continueAsNew() does not work if not returned or yielded

### ISSUE THREAD

**Issue by ConnorMcMahon** [Azure/azure-functions-durable-js#126]
**Describe the bug**
If `context.df.continueAsNew()` is called without calling `return` or `yield` on the response, then the orchestrator functions will just finish and not schedule a new execution.

**Investigative information**

- Durable Functions extension version: 1.8.0 or greater
- durable-functions npm module version: 1.3.1
- Language (JavaScript/TypeScript) and version: JS
- Node.js version: any?

**Comment by davidmrdavid** [comment]
@ConnorMcMahon , won't this be a breaking change for existing users of continueAsNew? If we don't return a Task, won't yield'ing now stop working?

**Comment by ConnorMcMahon** [comment]
The idea is that we would still return a Task, but also work if it is just called and not returned/yielded as a Task.

**Comment by davidmrdavid** [comment]
Closing as its already been fixed
