### ISSUE TITLE
Microsoft.Azure.WebJobs.Extensions.DurableTask 2.0 ?

### ISSUE THREAD

**Issue by MaxHogervorst** [Azure/azure-functions-durable-js#130]
When can we use Microsoft.Azure.WebJobs.Extensions.DurableTask 2.0.0 with javascript?

**Comment by cgillum** [comment]
You can use it now using the following command:

```
func extensions install -p Microsoft.Azure.WebJobs.Extensions.DurableTask -v 2.0.0
```

The caveat to this is that it's not yet available for selection in function templates nor is it included in extension bundles. Those updates are being worked on and will be available in the next month or two.

Let me know if you need further clarification on this.
