### ISSUE TITLE
Allow orchestrations to signal entities

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-js#134]
In JavaScript, orchestrations can call entities (two-way) using `callEntity`, but there is no API for doing one-way signals (`signalEntity`). We should add this API for the sake of parity.

**Comment by davidmrdavid** [comment]
I'll take over this issue, as mentioned in: https://github.com/Azure/azure-functions-durable-extension/issues/1115

**Comment by hossam-nasr** [comment]
Closing in favor of #327
