### ISSUE TITLE
Axios errors are re-thrown as strings

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-js#150]
### Problem
In the `DurableOrchestrationClient` class, all axios errors are caught and rethrown as strings. This is not good practice in JavaScript and can make debugging harder.

I discovered this when using **nock** to mock HTTP requests (the library was helpful enough to point out this problem to me).

### Proposal
Instead of catching axios errors, just let the error be raised as-is to the caller. Alternatively we could wrap the error in an error of our own, but I'm not sure there's much value added there.

**Comment by anthonychu** [comment]
May be related to https://github.com/Azure/azure-functions-durable-js/pull/129#issuecomment-572300429. I agree we should throw objects, but ensure they are serialized properly when writing to logs or propagating the errors to other functions.

I think some Axios objects have circular references that need special handling when serializing.
