### ISSUE TITLE
context.df.task.any ignores timeout (TypeScript)

### ISSUE THREAD

**Issue by lechnerc77** [Azure/azure-functions-durable-js#153]
**Describe the bug**
Setup is an an orchestrator with a timer and an activity in accordance to the documentation on [error handling](https://docs.microsoft.com/en-US/azure/azure-functions/durable/durable-functions-error-handling?tabs=javascript#function-timeouts)

To reproduce the error the activity can be switched to a sleep mode for 10 seconds or to an infinite loop (see source code). The timeout is set to 2 seconds, the activity will therefor run longer

The two tasks are called via context.df.task.any. However the timer is ignored and the orchestrator waits until the execution of the activity finished. 

**Investigative information**

- Durable Functions extension version: 2.1.0 (same error when using extension bundle)
- durable-functions npm module version: 1.3.2
- Language (JavaScript/TypeScript) and version: TypeScript 3.4.5
- Node.js version: 10.18.0

**To Reproduce**
See repository [https://github.com/lechnerc77/DurableFunctionErrorWithTaskAny](https://github.com/lechnerc77/DurableFunctionErrorWithTaskAny)

**Expected behavior**
The timer wins the race condition with task.any

**Actual behavior**
The framework always waits until the activity is finished. The timer is basically ignored although the table entries in the storage show that the event "timer fired" was raised

**Comment by ConnorMcMahon** [comment]
We have a fix for this [here](https://github.com/Azure/azure-functions-durable-js/pull/151). 

I was waiting to get another fix or two done for release 1.3.3, but if this is a blocker, I can do a release in the next day or two.

**Comment by lechnerc77** [comment]
If the release 1.3.3 is shipped in the next two weeks, everything is fine. If not a preliminary release would be great (no productive issue, but needed for customer demo)

**Comment by lechnerc77** [comment]
The newly release version 1.3.3 solves the issue as promised. I close the issue as successfully resolved
