### ISSUE TITLE
Rename DurableOrchestrationClient to DurableClient

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-js#154]
Now that `DurableOrchestrationClient` supports entity operations in Durable 2.x, we should rename it to `DurableClient`. This also makes it consistent with the binding type in function.json.

To make this a non-breaking change, we should continue to support `DurableOrchestrationClient`, but mark it as deprecated. I'm not sure what the official way to do this is in TypeScript, but apparently you do this in JS using the [@deprecated](https://jsdoc.app/tags-deprecated.html) JSDoc syntax.

**Comment by hossam-nasr** [comment]
Discussed this offline. Let's just do this in v3.x (without keeping the old name around), and it's not necessary to do this in v2.x, so closing this issue.
