### ISSUE TITLE
Add Durable Entities template

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-durable-js#166]
Would be great :) Also - the TS template for Durable Orchestration says "JS" I think?

**Comment by anthonychu** [comment]
Yes! Do you think it should look like the current Durable Functions templates and contain 2 functions (entity function + HTTP client)?

This would need to be only visible when v2 of bundles is being used (is this possible?). @cgillum how did you add the v2 Durable templates?

// @soninaren

**Comment by mhoeger** [comment]
I think it would be nice to have the 2 functions like the 3 with traditional durable! When I was testing it out, I copied the starter and entity function code from docs as a starting point

**Comment by anthonychu** [comment]
Created issue to track all templates here + a repo with samples to base the templates on: https://github.com/Azure/azure-functions-durable-extension/issues/1404

**Comment by lilyjma** [comment]
Just checked - Entity templates are available now. Also, TS template correctly says TS. Closing the issue
