### ISSUE TITLE
Error handling/propagation.

### ISSUE THREAD

**Issue by kashimiz** [Azure/azure-functions-durable-js#18]
Unhandled exceptions thrown by activities and sub-orchestrators should be propagated back to the calling orchestrator.

**Comment by KieranDaviesV** [comment]
@kashimiz Hey did you ever fix this? When i try to propagate my errors it returns an usable error object

**Comment by cgillum** [comment]
Hi @KieranDaviesV, this sounds like a different problem from what this issue was originally tracking. I suggest you open a new issue for the problem you're encountering.
