### ISSUE TITLE
Refresh Node versions in build matrix

### ISSUE THREAD

**Issue by aaronpowell** [Azure/azure-functions-durable-js#187]
The matrix defined in the `azure-pipelines.yml` has Node 8 & 10 as the two tested versions, but this is out of date on a) the supported runtimes from the Node Functions host and b) is using unsupported Node versions.

Referring to the [release schedule for Node](https://nodejs.org/en/about/releases/) and [end of life list](https://github.com/nodejs/Release#end-of-life-releases) v8 ceased LTS support at the start of 2020 and v10 will be going into maintenance mode in May 2020.

Given that the Functions Node Host dropped support for 8 in v3 I'd suggest it be dropped as a requirement for passing builds and that v12 be added (as that's supported by the Functions Host).

It might also be worthwhile adding v14 to the test matrix, but in a 'non-mandatory on passing' mode so that the code is pre-emptively tested against the upcoming LTS release.

**Comment by bnb** [comment]
>Given that the Functions Node Host dropped support for 8 in v3 I'd suggest it be dropped as a requirement for passing builds and that v12 be added (as that's supported by the Functions Host).

+1 to this, and to adding v14 to the test matrix as a pre-emptive check.

**Comment by aaronpowell** [comment]
Having done some research I've noticed that Functions v2, which Durable supports, [still supports Node 8](https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions#languages), but I'm not sure if you can select it in the portal when creating.

**Comment by bnb** [comment]
It's also worth noting that the EOL of Node.js 8 wasn't a normal EOL. It happened 4 months early due to the EOL of OpenSSL 1.0.2 (LTS). As such, any vulnerabilities that are discovered in the  OpenSSL 1.0.2 release line (which is the release line in Node.js 8) will be unpatched both in OpenSSL and in Node.js.

**Comment by ConnorMcMahon** [comment]
We should definitely at least add Node v12 to the test matrix.

I'm mixed on Node v14, as we don't support it in any versions of Azure Functions, but if we add it as a non-required section, I'm not opposed.

Hoping that @mhoeger can weigh in a bit on Node v8, and whether we have any official deprecation plan there.

**Comment by aaronpowell** [comment]
I know 14 is not currently supported, which is why I think it could be worth including but set a condition to not fail the build if it fails (so it's more an FYI run), as at some point 14 will be supported (so that Functions stays on track with Node releases).

**Comment by davidmrdavid** [comment]
@aaronpowell , @bnb 
Would this change only require updating our CI pipeline or would it have ramifications to the entire SDK, say, by requiring customer apps to also update to a newer node version if they currently use node ~8?

My impression is that we could get away with only a CI check, but I want to triple check.

**Comment by bnb** [comment]
The request here as I understand it is to update CI. I could be misinformed (in which case I'd be _extremely_ concerned that a repo's CI would directly affect customers) but that would only affect this repo and wouldn't touch customers.

The only caveat there is that if there are customers on Node.js v8, the CI builds will not pick up potential issues. That said, it would probably be good to work with customers if issues do come up on upgrading a potentially insecure runtime rather than prioritizing perpetually supporting it.

**Comment by mhoeger** [comment]
Sorry for the delay in weighing in on this - V2 supports both Node.js v8 and v10, and we don't have formal plans to deprecate support for v8 currently (cc: @dariagrigoriu who has put a lot of thought into this too). In my mind, it's a little similar to how we still support Functions V1 which supports Node.js v6 (although there are fundamental engineering reasons that prevent us from adding **any** other Node.js versions in V1). 

Worth noting too that Functions V3 (the latest version) supports v10, v12, and will support v14 when it moves from Current to LTS.

**Comment by aaronpowell** [comment]
@davidmrdavid the intent of this issue is to remove Node.js v8 and add v12 to the test matrix, and as @bnb said, it'd be better to work with customers who are still on v8 to ensure that there aren't potential issues being introduced.

It might be possible to do something more tricky with the build pipeline to allow a compile/test against v8 but skip linting, since linting is still done on the other versions, but then the pipeline is a bit more complex to manage.

**Comment by aaronpowell** [comment]
I decided to create a PR that shows an expanded matrix (#192), but it does include all the changes of #169 to illustrate the possibility of including Node.js v8 in the coverage matrix.

Here's the Azure Pipelines run with it all green - https://azfunc.visualstudio.com/Azure%20Functions/_build/results?buildId=5815&view=logs&j=14dfd0ae-31cc-5f86-98ae-9d9f863e832e

**Comment by davidmrdavid** [comment]
@aaronpowell , thanks so much for doing this 😄 . I'll continue our conversation in #192 .

**Comment by aaronpowell** [comment]
No problems @davidmrdavid.

I always figure that if I'm raising something, I should try and fix it too. 😉

**Comment by davidmrdavid** [comment]
Done in https://github.com/Azure/azure-functions-durable-js/pull/192
Thanks for the great discussion folks! I'll close this issue for now.
