### ISSUE TITLE
Add Linux to the build matrix

### ISSUE THREAD

**Issue by aaronpowell** [Azure/azure-functions-durable-js#188]
_Somewhat related to #187_

Currently, the builds only run on Windows agents, but given that Functions supports both Windows and Linux hosts, it'd be worthwhile running the tests on Linux as well. In theory there shouldn't be any difference between the two on the Node runtime, but more test coverage can't hurt.

**Comment by davidmrdavid** [comment]
I believe our current build matrix runs on linux. Closing this as a result
