### ISSUE TITLE
Javascript Activity Function Timeout never fails

### ISSUE THREAD

**Issue by gorillapower** [Azure/azure-functions-durable-js#19]
I wanted to confirm this behaviour. I have an activity function running a on a consumption plan that timesout after 10mins. However, the javascript orchestrator still remains in a 'running' state. I tried using the timers to complete the orchestration, but i guess its still waiting for all tasks to complete?

Can anyone confirm this behaviour and if so Is there a work around? Is there a way to perhaps cancel an activity function?

**Comment by kashimiz** [comment]
You're correct; the orchestrator function will be in a Running state until all its activity functions' Tasks have completed. An activity function that times out on the consumption plan will not have its corresponding Task complete in the orchestrator. This is a known issue and we're tracking it at Azure/azure-functions-durable-extension#338.

There is currently no way to cancel an activity function. If you're willing to leave your orchestrator in Running state and move forward with its final result, you could potentially use durable timers and the SetCustomStatus method as an ersatz output field and call it with your return value if your timeout timer Task finishes first. It's by no means a perfect workaround, but it's the best I can think of at the moment.

**Comment by gorillapower** [comment]
Thanks for the feedback @kashimiz. I took a look around the javascript API and i dont think the SetCustomStatus is available yet. The other option would be to manipulate the table storage directly to fake a complete state on the activity function, but im not even sure that will work.

**Comment by kashimiz** [comment]
This is true; Durable JS is still in preview status, so functionality is still being added. (SetCustomStatus is the last remaining piece of the DurableOrchestrationContext API, and will be in our next release.)

Manipulating the table storage alone wouldn't cause the activity function to be read as completed; a message is also added to the control queue to prompt the orchestrator to replay. That said, we generally advise against directly manipulating the backing tables and queues given the potential for things to go wrong.
