### ISSUE TITLE
using context.df.callHttp causing the request to get stuck at "Running" status

### ISSUE THREAD

**Issue by louiealmeda** [Azure/azure-functions-durable-js#191]
**Describe the bug**
I've tried this couple of times in my local environment and in Azure Portal, and I am experiencing the same scenario.

```
const df = require("durable-functions");

module.exports = df.orchestrator(function* (context) {
    const outputs = [];

    // Replace "Hello" with the name of your Durable Activity Function.
    outputs.push(yield context.df.callActivity("Hello1", "Tokyo"));

    return outputs;
});
```
I have a durable function that is perfectly working, and able to do a GET request. And GET the statusQueryGetUri which provides a "Completed" `runtimeStatus` All good.

----

Adding in a callHttp request like the code below, causes all requests' runtimeStatus to get stuck at "Running" and never completes nor fails. 

```
const df = require("durable-functions");

module.exports = df.orchestrator(function* (context) {
    const outputs = [];

    // Replace "Hello" with the name of your Durable Activity Function.
    outputs.push(yield context.df.callActivity("Hello1", "Tokyo"));
    
    const response = yield context.df.callHttp("GET", "https://conduit.productionready.io/api/articles?limit=10&offset=0")
    outputs.push(response)

    return outputs;
});
```

**Investigative information**

- Durable Functions extension version: 
- durable-functions npm module version: ^1.4.1
- Language (JavaScript/TypeScript) and version: Javascript
- Node.js version: 10

***If deployed to Azure App Service***

- Timeframe issue observed: 2020-05-29T11:39:24Z
- Function App name: durable-function-trial
- Function name(s): DurableFunctionsHttpStart1
- Region: East Asia
- Orchestration instance ID(s): 3cf7cc324f274ce3b4fd59d5ca83fd06

> If you don't want to share your Function App name or Functions names on GitHub, please be sure to provide your Invocation ID, Timestamp, and Region - we can use this to look up your Function App/Function. Provide an invocation id per Function. See the [Functions Host wiki](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately) for more details.

**To Reproduce**

1. Create a new JS Functions app in Azure Portal
2. `npm install durable-functions` using kudu
3. create an activity, orchestrator and http trigger
4. Test and HTTP trigger should be working correctly, orchestration instance gets Completed
5. Add in a callHTTP before the return value in the Orchestrator
```
const response = yield context.df.callHttp("GET", "https://conduit.productionready.io/api/articles?limit=10&offset=0")
    outputs.push(response)
```
6. Test the function again
7. The orchestration instance gets stuck in "Running"

> While not required, providing your orchestrator's source code in anonymized form is often very helpful when investigating unexpected orchestrator behavior.

**Expected behavior**
The orchestration instance will complete running and will provide return the response from callHttp

**Actual behavior**
The orchestration instance get stuck in "Running" state. Does not even Fail

**Screenshots**

**Known workarounds**
I have not seen any workarounds as of the moment

**Additional context**

- Development environment: Azure Portal, but also tried this in local using VS Code and same behavior
- Links to source
- Additional bindings used
- Function invocation IDs

**Comment by davidmrdavid** [comment]
Thanks for reaching out @louiealmeda. Just want to let you know that I'll be looking at this and will get back to you with updates as soon as possible.
⚡ ⚡

**Comment by davidmrdavid** [comment]
@louiealmeda 
I think I can reproduce this. From what I gather, `callHttp` appears to be completely broken. If you remove the activity call from the orchestrator, does the remaining `callHttp` still fail?

Also, would you mind sharing how your `host.json` and `local.settings.json` roughly look like for this reproducer? In this regard, do you have `FUNCTIONS_V2_COMPATIBILITY_MODE` set to true in your `local.settings.json` file and did you keep the bundles configuration intact in `host.json` or did you remove it?

**Comment by davidmrdavid** [comment]
Hi again! So I did some more digging and I can only reproduce this with a [durable-extension](https://github.com/Azure/azure-functions-durable-extension) (.NET framework that powers Durable Functions) installation of version lower than `2.0.0`. 

It appears that `callHttp` was introduced with `durable-extension` v2 in mind, and it is not supported for versions in `1.x`. 

With that in mind, we have two options to get you unstuck. The first is to manually install `durable-extension` v2 via an `extensions.csproj` file. You may find instructions to do this in the "Debugging end-to-end with Durable Extension" section of our [contributor's guide](https://github.com/Azure/azure-functions-durable-js/blob/dev/CONTRIBUTING.md). The second option would be to wait until the extension bundles, our abstraction over .NET installations, rolls out with a `v2` update.

Please let me know if any of this did not make sense! Happy to help you update your local extension version in case you need a helping hand with that as well. ⚡ ⚡

**Comment by louiealmeda** [comment]
Thanks for investigating this @davidmrdavid!
 
> I think I can reproduce this. From what I gather, callHttp appears to be completely broken. If you remove the activity call from the orchestrator, does the remaining callHttp still fail?

yes it works again when I remove the callHttp

-----

> Also, would you mind sharing how your host.json and local.settings.json roughly look like for this reproducer? In this regard, do you have FUNCTIONS_V2_COMPATIBILITY_MODE set to true in your local.settings.json file and did you keep the bundles configuration intact in host.json or did you remove it?

host.json, havent touched it, this was generated by Azure Portal
```
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 2.0.0)"
  }
}
```

I've tried adding `FUNCTIONS_V2_COMPATIBILITY_MODE` with a value of `true` to the Application Settings just now, but it is still behaving the same way.

------

> It appears that callHttp was introduced with durable-extension v2 in mind, and it is not supported for versions in 1.x.

Ahh this was one of my suspicions that I raised on a related issue [#53927](https://github.com/MicrosoftDocs/azure-docs/issues/53927#issue-611394104) if I understand your point correctly.

> The second option would be to wait until the extension bundles, our abstraction over .NET installations, rolls out with a v2 update.

So for JS, are you pertaining to this [npm package](https://www.npmjs.com/package/durable-functions)?

Meaning the npm package for v2 is indeed not yet available? May I know if there is a schedule for that? :) 

---

I'll try your recommendation about installing it manually. I'll post my progress here.

Thanks heaps!

**Comment by louiealmeda** [comment]
Thanks @davidmrdavid, your explanation made perfect sense.

I was able to make it work both in my local environment and in azure portal by adding in the `extensions.csproj`!

---

### Summary on how to make callHttp work for Javascript Azure Durable Functions

1. Remove `extensionBundle` from `your host.json`
```
///mine become just
{
  "version": "2.0"
}
```

2. Add an `extensions.csproj` in the root directory of your function app. 
  a. Use the contents from [this sample extensions.csproj file](https://github.com/Azure/azure-functions-durable-js/blob/dev/samples/extensions.csproj)
  b. Make sure to use the latest version of DurableTask which can be seen [here](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DurableTask/)
3. Run `func extensions install` in the root directory of your functions app
  a. If you're in azure portal, you can do this in the terminal of `App Service Editor` under `Development tools`
  b. you might need to `npm install -g azure-functions-core-tools@2`

Should be working as expected by now.

---

I think it will help a lot of people if the extensions setup is explicitly covered in the documentation of callHttp.

Is there a published roadmap on when the extension bundle is being released? It's quite a bit of additional setup and troubleshooting. 

Thanks for troubleshooting this with me david, I am now able to proceed with my development 🙂 💯

**Comment by davidmrdavid** [comment]
You got it @louiealmeda . I do agree that the `callHttp` caveat should should have been better documented. We're looking into adding it to our IntelliSense tooltips and I'll look to having it in our next release of `durable-functions` in npm.

I don't know of a published roadmap for the extension bundles situation, but I will update this thread if I find anything out. In the meantime, good luck moving forward 😸!
