### ISSUE TITLE
millisecond field in ISO8601 string value is changed unexpectedly between starter and orchestrator

### ISSUE THREAD

**Issue by hihorika** [Azure/azure-functions-durable-js#208]
**Describe the bug**
A clear and concise description of what the bug is. Please make an effort to fill in all the sections below; the information will help us investigate your issue.

**Investigative information**

- Durable Functions extension version: 1.8.5
- durable-functions npm module version: 1.4.3
- Language (JavaScript/TypeScript) and version: TypeScript 3.3.3
- Node.js version: v12.18.0

***If deployed to Azure App Service***
-> This is reproducable on local debugging.

**To Reproduce**

1. Create Orchestrator function
```ts
import * as df from "durable-functions"

const orchestrator = df.orchestrator(function* (context) {
  const msg: any = context.df.getInput();
  context.log.info(msg);
  return;
});

export default orchestrator;
```
2. Create HTTP Starter function
```ts
import * as df from "durable-functions"
import { AzureFunction, Context, HttpRequest } from "@azure/functions"

const httpStart: AzureFunction = async function (context: Context, req: HttpRequest): Promise<any> {
    const client = df.getClient(context);

    const instanceId = await client.startNew(req.params.functionName, undefined, "2020-07-14T10:38:45.300+09:00");

    context.log(`Started orchestration with ID = '${instanceId}'.`);

    return client.createCheckStatusResponse(context.bindingData.req, instanceId);
};

export default httpStart;
```
this function starts the orchestrator with a ISO8601 formatted ***string*** value (i.e. "2020-07-14T10:38:45.300+09:00", **not** DateTime object)

3. Execute the HTTP starter function

**Expected behavior**
`2020-07-14T10:38:45.300+09:00` would be outputted in console by the orchestrator.

**Actual behavior**
`2020-07-14T10:38:45.3+09:00` is outputted in console.
some digits, which are `0`, in millisecond field are removed.

**Screenshots**
Debuging in VScode
![image](https://user-images.githubusercontent.com/37284286/87780064-e0175180-c868-11ea-8acb-5e31d8c74254.png)

**Comment by hihorika** [comment]
I confirmed that this issue doesn't happen on C# Durable Function.

Debugging on Visual Studio.
![image](https://user-images.githubusercontent.com/37284286/87868053-72d10100-c9cd-11ea-9055-7dda551ad147.png)

It seems that this is JS library issue.

**Comment by davidmrdavid** [comment]
Hi @hihorika! 

Just a heads up that we've started this investigation. As far as I can tell, this is not occurring at the level of the Durable Functions SDK, so I believe the nodejs worker, or some other dependency, is responsible for dropping the `0`s. I'll check with @mhoeger tomorrow to learn where in the worker we could be modifying this string.  That's all for now! ⚡ ⚡

**Comment by davidmrdavid** [comment]
Hey @hihorika 

We're still investigating this, but I want to make sure the customer has a workaround. We currently believe the string is being parsed as a date internally, and then being serialized back to a string, losing those 0s in the process. As a temporary workaround, the customer could simply pre-pend or append an extra character (like a ".") to avoid the implicit casting to Date. Then, the user can remove it on the other side. I realize this is an awkward solution, but I wanted to make sure the user has a workaround.

**Comment by hihorika** [comment]
Thanks @davidmrdavid 
I appreciate your help.

I already have sent the following code, which complements 0s into the millisecond field forcefully by `String#replace`, as workaround to our customer.
Of course this is awkward too.

```ts
  const datetimeStringZeroPadding = datetimeString.replace(
    /(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})(\.\d{1,3})?([+\-]\d{2}:\d{2})/,
    (original, datetime, millisecond, timezone) => `${datetime}${millisecond ? millisecond.padEnd(4, '0') : '.000'}${timezone}`
  )
```

I'm asking the customer if the customer can accept this.

But I think the real resolution for this issue is to fix the following process you wrote.

> We currently believe the string is being parsed as a date internally, and then being serialized back to a string, losing those 0s in the process.

Could you please investigate what is a root cause and let me know ETA of the fix?

**Comment by hihorika** [comment]
And you said this issue is not occurring at the level of the Durable Functions SDK.
I understand that.

So, please transfer this issue to an appropriate repository ([azure-functions-nodejs-worker](https://github.com/Azure/azure-functions-nodejs-worker) or [azure-functions-host](https://github.com/Azure/azure-functions-host) ?) if you can.

**Comment by davidmrdavid** [comment]
Yup! Let me follow-up internally with the Functions core team to figure where precisely we should transfer this, if at all :) .

**Comment by davidmrdavid** [comment]
Closing since the fix was merged!

**Comment by hihorika** [comment]
@davidmrdavid 
Thank you for your help!
