### ISSUE TITLE
Local Testing doesn't show logging output for the Orchestrator and Activity Functions

### ISSUE THREAD

**Issue by rcg-dev** [Azure/azure-functions-durable-js#213]
I have a function app that utilizes durable functions. It has some context.log()'s here and there. When it runs in the cloud, all 3 (starter, orchestrator, and activity) functions show the proper and expected log outputs. However when running it locally, the orchestrator and activity functions, sporadically don't log anything. I reached out to Azure Support and they told me to create an issue because the themselves were unsure of why this was happening.

To add more context:
I have another test function app I made on the same machine and it is working and logging just fine. It is specifically this one function app that is really buggy and doesn't log sometimes (very unpredictably).

host.json:
`{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  },
  "extensions": {
    "http": {
      "routePrefix": ""
    },
    "durableTask": {
      "hubName": "myHubName"
    }
  }
}
`

**Comment by davidmrdavid** [comment]
Hey @rcg-dev ,

Thank you for reaching out. Do you have a reliable minimal reproducer you could share? That would help us get to the bottom of this :) 

Thanks!
⚡ ⚡

**Comment by rcg-dev** [comment]
Hey @davidmrdavid,

Here is a simplified version of my durable function. In the time since I opened this issue to now I have discovered the reason but not the reasoning. So during local testing in my host.json my **hubName** was set to the same value as the deployed functions were using. Changing the hubName to some other value, instantly gave me logging and reverting back to using the same one as the deployed functions made the logging disappear. 

I must add that in my local.settings.json I had my  **AzureWebJobsStorage** value not set to `UseDevelopmentStorage=true` but instead had an Azure Storage connection string in there. (that probably allowed the direct read/write of logs into the cloud and therefore redirected my outputs? I am not sure of the mechanics behind it. However I am sure that I need to use different names for different environment for my `hubName`

**Comment by davidmrdavid** [comment]
Hey @rcg-dev , I'm pinging some internal folks to see if we can reason about your fix. In the meantime, I don't see the attached reproducer. Where is it again?

**Comment by rcg-dev** [comment]
Hey @davidmrdavid it didn't let me upload the zip directly, so here is a google drive link to it. [https://drive.google.com/file/d/1RWDnsahZLbKjc2nWiTUJQAUHQm0Wpxt2/view?usp=sharing](url)

**Comment by davidmrdavid** [comment]
Hi @rcg-dev ,

Thank you for the reproducer. I've checked with some colleagues and we believe it's possible that your functions aren't even running locally. That is, you may be running onto a task hub conflict issue leading your messages to get silently stolen by an app running on azure. 

I want to do a bit more digging on my end but, in the meantime, can you confirm whether or not your **HTTP Trigger logs are also failing to show up**? If so, then we may have to change our working theory. Thanks!

**Comment by rcg-dev** [comment]
Hey @davidmrdavid ,
My http trigger logs do show up - no problem. I think the messages are being stolen by the app, which makes a lot of sense now.

**Comment by davidmrdavid** [comment]
HI @rcg-dev ,

Just one more update on this front. I would suggest reading up [this ](**url**) document, especially the note at the bottom, as it explains that sharing TaskHubNames can lead to function apps competing for work message queues, which can lead to all sorts of problems.

I'm glad we figured this one out though! Thank you for working with us and let us know if you need anything else in the future! For now, the fix is to use different TaskHubNames and/or to use local development storage. Good luck!
