### ISSUE TITLE
Question: Getting value from context.bindings.starter

### ISSUE THREAD

**Issue by simonagren** [Azure/azure-functions-durable-js#22]
Hi,
I might have misunderstood how durable functions work. 
But I have made:
1. An HttPTrigger, that starts an Orchestration. with
```
context.bindings.starter = [{
            FunctionName: "OTestarDur1",
            Input: siteName,
        }];
```
2. The orchestration calls an activity and gets all the lists in SharePoint.

```
const lists = yield context.df.callActivity("ATestarDur1", site);
return lists;

```
All of this works. But is it possible back in the HttpTrigger to get the value of the lists I returned?
From the context.bindings.starter maybe?

/Simon

**Comment by kashimiz** [comment]
Hi @simonagren ,

It's not possible with the current support for JavaScript (npm: durable-functions 1.0.0) but the next release of the module, which will be available before the end of this year and pairs with the upcoming 1.7.0 release of the Durable Functions extension (Microsoft.Azure.WebJobs.Extensions.DurableTask), will support this.

That release adds the [DurableOrchestrationClient API](https://azure.github.io/azure-functions-durable-extension/api/Microsoft.Azure.WebJobs.DurableOrchestrationClient.html#Microsoft_Azure_WebJobs_DurableOrchestrationClient_GetStatusAsync_System_String_System_Boolean_System_Boolean_) that's available in C#. With that, you'll be able to use methods like [WaitForCompletionOrCreateCheckStatusResponse](https://azure.github.io/azure-functions-durable-extension/api/Microsoft.Azure.WebJobs.DurableOrchestrationClient.html#Microsoft_Azure_WebJobs_DurableOrchestrationClient_WaitForCompletionOrCreateCheckStatusResponseAsync_System_Net_Http_HttpRequestMessage_System_String_System_TimeSpan_System_TimeSpan_) to get the output of your orchestrator directly (if it completes within the timeout period) or the location of a status endpoint you can periodically check for completion.

Keep in mind that an HTTP triggered function should return a response in relatively short order to the client that called it, despite kicking off a long-running operation. One solution to this is the [async HTTP API pattern](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-overview#pattern-3-async-http-apis) which is built into Durable Functions.

Here's an example of how the upcoming API might be used in an HTTP-triggered starter function. Depending on whether it receives a JSON object shaped like a [DurableOrchestrationStatus](https://github.com/Azure/azure-functions-durable-extension/blob/master/src/WebJobs.Extensions.DurableTask/DurableOrchestrationStatus.cs) (orchestration has not completed) or something else (orchestration has completed, result returned), the client that calls this function could poll the endpoint provided by the status object until it completes, or proceed with the result respectively.

```javascript
const df = require("durable-functions");

const timeout = "timeout";
const retryInterval = "retryInterval";

module.exports = async function (context, req) {
    const client = df.getClient(context);
    const instanceId = await client.startNew(req.params.functionName, undefined, req.body);

    context.log(`Started orchestration with ID = '${instanceId}'.`);

    const timeoutInMilliseconds = getTimeInSeconds(req, timeout) || 30000;
    const retryIntervalInMilliseconds = getTimeInSeconds(req, retryInterval) || 1000;

    return client.waitForCompletionOrCreateCheckStatusResponse(
        context.bindingData.req,
        instanceId,
        timeoutInMilliseconds,
        retryIntervalInMilliseconds);
};

function getTimeInMilliseconds (req, queryParameterName) {
    const queryValue = req.query[queryParameterName];
    return queryValue
        ? queryValue // expected to be in seconds
        * 1000 : undefined;
}
```

**Comment by simonagren** [comment]
Thanks for an incredible answer.

My though was to do this:
1. Http call to start Orchestration1.

2. Orchestration1 starts Activity1 and yields to get all lists in Sharepoint.
Then we loop the lists, starts suborchestration Orchestration2, in parallell (promises)

3. Orchestration2 starts activity2 that yields and gets all items for the list.
We loop trough the items and starts activity 3 in parallell (promises)

4. Activity 3 get sharinginformation from the item and returns the value.

5. All promises on all levels are revolved and Orchestration1 returns all items that's externally shared.

Do you Think this is poasible? Or would any other partern be vetter for this? 😀

**Comment by kashimiz** [comment]
Thank you! I'm glad it helped. 😄 "Retrieving lots of stuff in parallel" is a classic application of the fan-out/fan-in scenario, so what you propose is totally doable and makes sense. Sarah Drasner and Maxime Rouiller, two of our cloud developer advocates, collaborated on an article that covers a similar scenario [here](https://css-tricks.com/durable-functions-fan-out-fan-in-patterns/).

You can choose how to nest your sub-orchestrators:

- Orchestration1 calls
  - Orchestration2 and
  - Orchestration3

or

- Orchestration1 calls
  - Orchestration2 calls
    - Orchestration3

I'm partial to the second structure, as you wouldn't have to wait on all of your Orchestration2 instances to complete before starting any instances of Orchestration3.

**Comment by simonagren** [comment]
Ok nice. Gonna look at the article.
So in my scenario I have to get the returnvalue, I need to wait for the update still, right?

Sry if the questions are a bit dumb, but I'm quite new to this 😀

**Comment by kashimiz** [comment]
No worries! Your questions aren't "dumb" at all.

Can you clarify what you mean by "the return value"? Do you mean the end result of your orchestration, e.g. the sharing information from all items in all SharePoint lists?

**Comment by simonagren** [comment]
Yeah Im essentially looping trough all lists that arent hidden.  Gets all items, and those who have unique role assignments(HasUniqueRoleAssignments) I'm checking the sharinginformation.

So the way I built it it efter all promises are done and all is returned back to the Orchestration1 I have a constant with all those items.

So my idea was to return the result all the way back to the user. 

And is that poasible currently or should I store the values somewhere else?

**Comment by simonagren** [comment]
So the "WaitForCompletionOrCreateCheckStatusResponse" is the key for getting the calue from the orchestrator?

My code looks quite similar to your last example :)

**Comment by kashimiz** [comment]
WaitForCompletionOrCreateCheckStatusResponse is a shortcut that returns the value from the orchestrator if and only if the orchestrator completes within the specified timeout. If the timeout expires before the orchestrator completes, WaitForCompletionOrCreateCheckStatusResponse  doesn't return the orchestrator's result (as it doesn't exist yet.) Instead it returns (along with other data) an endpoint where the client can continue checking the orchestrator's status. This pattern allows for the client that calls the starter function to receive a quick response instead of being left hanging with no response for an extended period of time. You will want whatever calls your HTTP starter function to be capable of handling **both** types of response. (If you use CreateCheckStatusResponse, you'll only need to handle the latter case, as it doesn't wait until a timeout period is up to return the endpoints.)

[The documentation](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-overview#pattern-3-async-http-apis) goes into how to use this pattern, and [this part](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-http-api) covers what the HTTP endpoints return. (Status can also be queried from the [OrchestrationClient](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-instance-management).)

**Comment by simonagren** [comment]
Thank you very much, I will read up on this :) Much appreciated!

**Comment by kashimiz** [comment]
Sure thing! Ping if you need any help.

**Comment by simonagren** [comment]
@kashimiz i really cant get callSubOrchestrator to work. Local debugging or in Azure.
Tried your example and more simple examples just calling one.  
I get no errors.
Any ideas?

**Comment by simonagren** [comment]
@kashimiz nevermind, it worked now. It was something with the Durabletask extension, so now it's sorted :)

**Comment by hanvyj** [comment]
> WaitForCompletionOrCreateCheckStatusResponse is a shortcut that directly returns the value from the orchestrator to the starter function if and only if the orchestrator completes within the specified timeout...

Just to check, this features isn't implemented yet but will be in the next release?

**Comment by simonagren** [comment]
@hanvyj exactly, not Implemented yet.

**Comment by hanvyj** [comment]
Thanks for clarifying. Are any of the options possible (even if it's polling status or something crude) to have a client wait and return the orchestrator's result? I'm not sure which of the options discussed above will work with v1.0.0!

**Comment by hanvyj** [comment]
> @hanvyj exactly, not Implemented yet.

Is there any way to work-around? I've tried polling the HTTP endpoint from within the client function, but it doesn't seem to trigger the function starting unti the client ends, is that right?

```
export async function run(context: Context, req: HttpRequest): Promise<any> {
  const id = uuid();

  const startArgs = [
    {
      FunctionName: "test-orchestrator",
      Input: req.params.functionName,
      InstanceId: id
    }
  ];

  context.bindings.starter = startArgs;
  
  logger.debug(`Checking status of ${req.params.functionName}, id: ${id}`);
  const result = await axios.get(`http://localhost:7071/runtime/webhooks/durabletask/instances/${id}`);

  return {
    body: result,
    status: HttpStatusCode.OK
  };
}
```
