### ISSUE TITLE
Improve performance for orchestrations with large history

### ISSUE THREAD

**Issue by ConnorMcMahon** [Azure/azure-functions-durable-js#221]
As orchestration history increases (especially for the fan-out/fan-in pattern), execution time increases in a roughly quadratic manner.

Fixing this will require a fairly large refactor.

**Workaround:**

Keep history shorter. This can be accomplished by batching work items into suborchestrations, so that each orchestration has smaller history.

**Comment by davidmrdavid** [comment]
This will be fixed in the next release
