### ISSUE TITLE
Problem in making a http post in azure function

### ISSUE THREAD

**Issue by ashima-24** [Azure/azure-functions-durable-js#223]
Hello everyone,

I am new to azure and wanted to implement a simple post http request in node,js,  I am trying to implement this code below:
but I am getting an error 503. can anyone know a better implementation other than this or could help on this?
`const df = require("durable-functions");

module.exports = df.orchestrator(function*(context){
   // const url = context.df.getInput();
    const response = yield context.df.callHttp("POST", "https://postman-echo.com/post")

consoloe.log(response);
    if (response.statusCode >= 400) {
        // handling of error codes goes here
    }

});`
![posttrial1](https://user-images.githubusercontent.com/44822013/99269819-bc6c1400-2826-11eb-8c32-5a6be266a302.png)

**Comment by davidmrdavid** [comment]
Hi @ashima-24 ,

Thanks for reaching out and sorry that you experienced this exception. Looking at your code, and at the error response, it would appear that the exception you experienced was a temporary outage in the Azure portal. I have two quick questions:

(1) Does your code work _locally_? Let me know if you need some help setting up your local environment
(2) Does this portal error persist even now?
(3) Can you share your `host.json`? I want to make sure you're using the latest version of extensionBundles: version 2.

Thanks!

**Comment by ashima-24** [comment]
Hello @davidmrdavid 

1. no i didn't test my code locally. I am using azure portal for testing
2. actually right now i am getting "Function host is not running."  error 503

3. and i have  this in my host.json file becuase as i was following one of the issues on this link https://github.com/Azure/azure-functions-durable-js/issues/191
{
  "version": "2.0",
 
}

**Comment by davidmrdavid** [comment]
Hi @ashima-24,

I see. I have three suggestions for you. First, `callHttp` is only available by extensionBundles v2 and, to use them, your  `host.json` should look as follows:

```JSON
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[2.*, 3.0.0)"
  }
}
```

Second, looking at the code you sent in your original comment, I see a typo that could explain the problem. You wrote `consoloe.log` when it should be `console.log`. Perhaps that's the issue?

Finally, if the two suggestions above fail, I would really recommend trying this out locally to make sure no coding-level errors are being made :) . You can easily set-up your local environment by following our guide here: https://docs.microsoft.com/en-us/azure/azure-functions/durable/quickstart-js-vscode .

Please let me know if any of these suggestions fixed your exception. If not, please send me a `.zip` file with your code and I'll try to reproduce the error myself :) 

Looking forward to getting this resolved!
⚡ ⚡

**Comment by ashima-24** [comment]
HI David, after changing the host.json file, as per your instructions, I tried to run the code again after correcting the typo which you found in the code. but then it says function is unreachable. Is there something missing?

**Comment by davidmrdavid** [comment]
There might be! In general, you could try trouble-shooting with this page: https://docs.microsoft.com/en-us/azure/azure-functions/functions-recover-storage-account

However, this seems simple enough so I suspect there's another configuration error. In general, we do not recommend using the portal to develop functions, it's mostly just a demo'ing tool. Would you mind setting up a local environment by following the guide here: https://docs.microsoft.com/en-us/azure/azure-functions/durable/quickstart-js-vscode

A local environment gives us more options to debug, so it would help me to get you unstuck :)

**Comment by davidmrdavid** [comment]
Closing since we haven't heard back in a few weeks
