### ISSUE TITLE
Creating Durable Function HTTP Starter cannot create anymoer durable functions such as Orchestrator or Activity 

### ISSUE THREAD

**Issue by Daksitha** [Azure/azure-functions-durable-js#225]
When I create a HTTP Starter function (or HTTP Orchestrator function or HTTP Activity function first) then I try to add the following functions by clicking + sign. The selection menu no longer shows any more durable functions in the list. It only contains HTTP trigger function and Timer trigger function. Could you help on this please

**Comment by davidmrdavid** [comment]
Hi @Daksitha,

Thank you for reaching out! Do you mind sending over a few screenshots of what you're seeing and describing the steps you're taking to get to that state? Thank you!

⚡  ⚡

**Comment by Daksitha** [comment]
Hi @davidmrdavid, 
Thank you for your promptly reply! 
yes, sure. Please refer below for the scenario I mentioned in my problem.  
1. Created a Function App with these settings
![1](https://user-images.githubusercontent.com/7329816/99380146-da3e8500-28c9-11eb-8189-1cae4b86f0a4.jpg)
2. Add a Durable Http Start function for the first time. Drop down menu has all the options
![2](https://user-images.githubusercontent.com/7329816/99380148-dad71b80-28c9-11eb-839d-b1c1f5fdd93a.jpg)
3. This is the default template
![4](https://user-images.githubusercontent.com/7329816/99380155-db6fb200-28c9-11eb-9235-cc782d250105.jpg)
4. Then I try to add the Orchestrator function again and it is no longer showing me all the options. 
![3](https://user-images.githubusercontent.com/7329816/99380153-db6fb200-28c9-11eb-983a-87e4c86cafe7.jpg)

**Comment by davidmrdavid** [comment]
Thanks! This looks like a UI bug in the portal. I'll notify the team in charge, we might need to move this ticket to a different repo though, I'll let you know :)

**Comment by refortie** [comment]
@Daksitha Hi, I'm from the UI team, could you please reach out to my email and I can help triage this further. refortie@microsoft.com

**Comment by ConnorMcMahon** [comment]
@Daksitha , can we close this issue now?

**Comment by Daksitha** [comment]
Yes, please :)
