### ISSUE TITLE
CosmosDB trigger inputParam no longer being passed in in 1.4.4

### ISSUE THREAD

**Issue by teresahoes** [Azure/azure-functions-durable-js#231]
**Describe the bug**
I have an orchestration that calls an activity with a a cosmosDB input parameter. 
    {
      "name": "report",
      "type": "cosmosDB",
      "databaseName": "%DATABASE_NAME%",
      "collectionName": "ssrsReports",
      "id": "{id}",
      "connectionStringSetting": "COSMOS_DB_CONNECTION",
      "direction": "in"
    }

Inside my activity - i access the report parameter out of the context bindings. 

module.exports = async function (context) {
    let reportDoc = context.bindings.report; 

...}

The report parameter holds the JSON of the associated document db record. 

This has been working fine for years for every durable function version until 1.4.4. 

with 1.4.4 the report input parameter is now undefined when the activity runs. 

**Investigative information**

- Durable Functions extension version:  3.x
- durable-functions npm module version: 1.4.4
- Language (JavaScript/TypeScript) and version: Javascript
- Node.js version: 12 lts

***If deployed to Azure App Service***

- Timeframe issue observed:  2020-12-23T17:46:18.891Z
- Function App name: azrfnsfunc/dev
- Function name(s): activity_get_report
- Region: north central us
- Orchestration instance ID(s): a32e223d87ac4eb5a510e05117326cd4

**Known workarounds**
Reverting to 1.4.3 resolves the issue

**Comment by davidmrdavid** [comment]
Hi @teresahoes, thank you for reaching out and sorry for my delayed reply. Do you mind sharing a `zip` file or clonable repo with a minimal reproducer for this? I want to make sure I've got as close of a reproducer to yours. Thank you, it would help us investigate this faster!

**Comment by teresahoes** [comment]
hi @davidmrdavid  -- thanks for your
[durablefunction.zip](https://github.com/Azure/azure-functions-durable-js/files/5953471/durablefunction.zip)
 reply. is this what you are looking for?  the issue is that in the context.bindings in my activity, i no longer receive the contents of the docdb as i did prior to 1.4.4.

**Comment by davidmrdavid** [comment]
That's indeed what I was looking for, thank you @teresahoes, I'll be taking a look at this starting shortly!

**Comment by davidmrdavid** [comment]
Hi @teresahoes,
I tried reproducing this today but I encountered the following exception when trying to build your `package.json` via `npm install`

```
PS C:\Users\david\source\repos\repros\durablefunction> npm install
npm WARN deprecated @hapi/hoek@8.2.5: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@klf_dev%2fcn-dao-azure-cosmosdb - Not found
npm ERR! 404 
npm ERR! 404  '@klf_dev/cn-dao-azure-cosmosdb@^1.3.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'durablefunction'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\david\AppData\Roaming\npm-cache\_logs\2021-02-11T22_49_33_056Z-debug.log
PS C:\Users\david\source\repos\repros\durablefunction> 
```

Do you see this as well?

**Comment by teresahoes** [comment]
Hi @davidmrdavid  -- sorry please remove any references to @klf_dev/<name>  in the package.json. they are internal packages not germaine to this test.

**Comment by davidmrdavid** [comment]
Hi @teresahoes, I was able to get a minimal reproducer working after adding a `partitionKey` property to the `"cosmosDB"` binding in your activity's `host.json`. Unfortunately, I was not able to get this to work without this value, even after downgrading to previous versions of durable-functions, so I suspect the issue is not a part of durable itself, but maybe that upgrading to the latest durable-functions version might be upgrading some other azure SDKs for javascript. That's just a theory though, because I've never seen this happen before.

Regardless, looking at [this](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2-input?tabs=javascript#queue-trigger-look-up-id-from-json-1) documentation suggests that `partitionKey` is a common and expected part of setting up the `cosmosDB` binding, at least as of the most recent docs, so perhaps the quickest path to mitigating this is to add that in.

Do you mind giving that a try? If that doesn't work, I might need to transfer this ticket to the CosmosDB repository as they are the subject matter experts here. I can help take care of that for you.

**Comment by teresahoes** [comment]
Ah That actually makes a lot of sense given some other recent issues we have had with the partition key.  We are connecting to an older instance of a cosmos db that doesn't have a partition key.

I will play around with adding this in and/or updating our cosmos db.

Thanks so much for your insight!



Sent from my Galaxy



-------- Original message --------

**Comment by teresahoes** [comment]
Hi @davidmrdavid  - i have been trying everything to get this to work, i did not have any luck with adding in partitioning. I can only get the input binding to work when i revert back to 1.4.3.  There is one spot where i see a difference and wonder if it is the cause of the issue.  See in the attached screen shot that the value in the data property in the bindingData is single quoted in the 1.4.3 version that works, but has extra quotes in the 1.4.5 version that doesnt work. In this case the value that is in the data property is the cosmodb id value. I wonder if that is messing up the ability to find the document.  
![screenshot-bindingdata](https://user-images.githubusercontent.com/14821548/108424720-63799680-71ee-11eb-8e9f-f46c0f17a42b.png)

i dont know how that data property is set, but its definitely different between the two versions. Is this something in the durable functions code or the cosmos db repo? If this isnt the right forum can you point me in the right direction? thanks so much!

**Comment by davidmrdavid** [comment]
Aha! I could see that being a problem. I think I know what's going on now, let me get back to you shortly!

**Comment by davidmrdavid** [comment]
For context, the reason for the extra quotes is that we recently introduced this utility function: https://github.com/Azure/azure-functions-durable-js/blob/c6e1844a3959fc37447c2a364ea0f8833a070852/src/utils.ts#L3

It very literally adds extra quotes to the inputs of activities to make sure that strings such as "3" don't accidentally get parsed as **the number 3** when de-serialized on the other end. In this case, since you're using the activity input at the `function.json`-level, it's possible that the input hasn't been de-serialized yet and so you get those double-quotes when interfacing with CosmosDB.

I'll loop in the right subject-matter experts to look for a fix.

**Comment by davidmrdavid** [comment]
For documentation's sake, this issue was introduced in: https://github.com/Azure/azure-functions-durable-js/pull/217

**Comment by davidmrdavid** [comment]
Hi @teresahoes, do you mind trying the following workaround?

In your orchestrator, pass your input to your activity as follows:

```JavaScript
yield context.df.callActivity("activity_get_report", { "myID": <ID value of valid docdb record>});
```

and then in the`function.json` of your **activity** modify the CosmosDB binding as follows

```
{
  "bindings": [
    {
      "name": "id",
      "type": "activityTrigger",
      "direction": "in"
    },
    {
      "name": "report",
      "type": "cosmosDB",
      "databaseName": "%DATABASE_NAME%",
      "collectionName": "ssrsReports",
      "id": "{myID}",
      "connectionStringSetting": "COSMOS_DB_CONNECTION",
      "direction": "in"
    }
  ],
  "disabled": false
}
```

For clarity's sake, the change is that the "id" **field** is now assigned to "{myID}" which corresponds to the key of your activity's input JSON.

Please let me know if that works! JSON objects should be getting serialized correctly, and this syntax should allow you to access the fields of your activity inputs (in this case that's `"myID"`) transparently. Thanks!

**Comment by teresahoes** [comment]
YAS!!!!!  works. thanks so much for this :)  Cheers.

**Comment by davidmrdavid** [comment]
🎉 🎉 
Glad to hear that worked.
Just as an FYI, we still have a string serialization problem in our hands, but now we're aware of it and we'll work on it behind the scenes to ensure that your previous solution can work again in the future. Thanks again :)
