### ISSUE TITLE
High Security Vulnerability with Axios Version 0.19.0

### ISSUE THREAD

**Issue by skholmesz** [Azure/azure-functions-durable-js#235]
Hey guys, my teams npm audit picked up that the ^0.19.0 version of Axios, used in your latest version (1.4.4). Has a recently discovered security vulnerability.

https://www.npmjs.com/advisories/1594
https://www.npmjs.com/package/axios/v/0.19.0

Can fix by updating to >0.21.1

![image](https://user-images.githubusercontent.com/77310847/104520167-8816a780-565f-11eb-8be7-97085061da79.png)

**Comment by davidmrdavid** [comment]
Thank you for this issue @skholmesz . We just released a new package without this dependency :) . Thanks again!! ⚡ ⚡
