### ISSUE TITLE
Question: Get the random generated instanceId

### ISSUE THREAD

**Issue by nafis00141** [Azure/azure-functions-durable-js#24]
[InstanceId: (Optional) The unique ID of the instance. If not specified, a random instance ID will be generated.](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-instance-management)

In the [sample](https://github.com/Azure/azure-functions-durable-js/blob/master/test/sample/HttpStartJS/index.js) `uuid` is used to create a InstanceId. But is there a wey to get the random generated instanceId?

**Comment by kashimiz** [comment]
It's not possible in the current release of the durable-functions npm package (1.0.0) to rely on the Durable Functions extension to generate a random instance ID. As of this comment, output bindings in JavaScript can only pass information out of a function; they can't receive information from the extension or host runtime, so there's no way for the extension to pass back the ID it's generated. You'll need to use a UUID- or GUID-generation module in your orchestration client function to create an instance ID for your orchestration for now. (This is identical to [what we do on the extension side](https://github.com/Azure/azure-functions-durable-extension/blob/c6d3ce6dd427f2c1b9659d0ef6776922da062f44/src/WebJobs.Extensions.DurableTask/DurableOrchestrationClient.cs#L85).)

We're currently porting the [DurableOrchestrationClient API](https://azure.github.io/azure-functions-durable-extension/api/Microsoft.Azure.WebJobs.DurableOrchestrationClient.html#methods) over to JavaScript for the next durable-functions npm release, which should drop before the end of 2018. That update will allow you to write orchestration client functions that get instance IDs from the extension, like this:

```javascript
const df = require("durable-functions");

module.exports = async function (context, req) {
    const client = df.getClient(context);
    const instanceId = await client.startNew(req.params.functionName, undefined, req.body);

    return client.createCheckStatusResponse(context.bindingData.req, instanceId);
};
```
