### ISSUE TITLE
Expose new typed interface

### ISSUE THREAD

**Issue by davidmrdavid** [Azure/azure-functions-durable-js#240]
We've had several proposals to improve our usage of TypeScript to better type our Durable interface for TypeScript customers. We have an almost-ready-to-merge PR with such changes here: https://github.com/Azure/azure-functions-durable-js/pull/195

It's about time we take it over the finish line :)

**Comment by hossam-nasr** [comment]
@davidmrdavid just wondering, should this issue be closed after #195 was merged?

**Comment by davidmrdavid** [comment]
Yes, please do @hossam-nasr

**Comment by davidmrdavid** [comment]
oh, I see it was closed. I'll close this one then
