### ISSUE TITLE
Fan Out doesn't appear to be scaling

### ISSUE THREAD

**Issue by jawa-the-hutt** [Azure/azure-functions-durable-js#241]
**Describe the bug**
I have an orchestrator function that calls an activity function over and over using the Fan Out/Fan In method.  The Activity function then goes out and hits a HTTP endpoint that load balances ACI containers that are being controlled by AKS via the KEDA autoscaler project.    We are using Puppeteer inside the containers to run a series of UI tests.  Each test generally take about 2-4 minutes to run and we run about 25 at the same time per container. So, the bulk of the actual CPU usage is passed off to the container and not the Function instance. 

What I think should be happening is that if I pass in 100 tests, then all 100 should be sent to the containers immediately, but what I'm finding is happening is that the `maxConcurrentActivityFunctions` setting is limiting how many tests will concurrently be sent.  If the setting is 3, then only 3 run at a time and as one test comes back from a container, another will start, but the limit is only 3.  This setting can be 10, 20, 50 or 100 and that will essentially be the concurrent tests that the containers will be processing.

I can look in the workItem queue for the Function host and see all the messages queued up in there.  Depending on the `maxConcurrentActivityFunctions` setting, these will sit in queue for 10-15 minutes (or more if I go really crazy and have a high total test count, but a low `maxConcurrentActivityFunctions` setting)

**Investigative information**

- Durable Functions extension version: 2.4.0
- durable-functions npm module version: 1.4.3
- Language (JavaScript/TypeScript) and version: Typescript 3.9.7
- Node.js version: 12

***If deployed to Azure App Service***

- Timeframe issue observed: `2021-01-29T02:33:40 GMT` to `2021-01-29T04:50:12 GMT`
- Function App name: `mea-browserless-fa-testsuite/dev` (this is on a consumption plan)
- Function name(s): `startTests`
- Region: `East US`
- Orchestration instance ID(s):
  - 458a8bd2270b42c58e9fd358f0299578
  -  996b1d2abac74d2fab1ed4e86a188397
  - 72d0c82fc23641da9ea0cde8fe593d21
  - df748c221d2c486e92802a6ea2bd71cd
  - 5a30085babd743728383c99298a50d0a
  - 8d04e51ae63744c1b2cf6646a66c7eaf
  - 36271bbc81a74e5487362f94dd6ace0d
  - 4ac183d509514e1880b55a760f658ae7
  - fc358c072a4243aa92cb5c1f6c23c33f
  - 5d834f2bf4754f05b07368c8146c911d
  - ae127ee3c8924d19a1b2bb31b132963f

**To Reproduce**
Can't really reproduce outside of our web app starting the test process.

**Expected behavior**
My understanding of how things should work is that if any messages sit in this queue for longer than a few seconds, then another instance should be spawned by the Scale Out Controller.  Thus all tests should be running within 30-60 seconds instead of taking 10 to 15+ minutes to start.

**Actual behavior**
No extra instances are spawned.  I can sit and watch in Application Insights and no 2nd instance will spawn.  The one caveat to this is when I set the `maxConcurrentActivityFunctions` setting high, like 100, then when all the tests start to come back at once and there is additional processing at the end to collate data and such, then the CPU will spike on the instance to the point that the Scale Out Controller will then spawn a second instance.

**Comment by jawa-the-hutt** [comment]
Want to add some additional information as this might be an issue with other settings in my host.json.  I went ahead and created a whole new Function App just to make sure there wasn't something corrupted or misconfigured somewhere that I couldn't find.  The new Function App behaved in the exact same manner as the old.

Here is my hosts.json
```
{
  "version": "2.0",
  "functionTimeout": "00:10:00",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    },
    "logLevel": {
      "Host.Triggers.DurableTask": "Warning",
      "Host.Aggregator": "Warning",
      "Host.Results": "Error",
      "Host.Startup": "Warning",
      "Host.Status": "Warning",
      "Host.LanguageWorkerConfig": "Warning",
      "Microsoft": "Warning",
      "Worker": "Warning",
      "DurableTask.Core": "Warning",
      "DurableTask.AzureStorage": "Warning",
      "DurableTask.DurableTaskListener": "Warning",
      "Function": "Warning"
    }
  },
  "extensions": {
    "durableTask": {
      "hubName": "startTests",
      "storageProvider": {
        "connectionStringName": "AzureWebJobsStorage",
        "controlQueueBatchSize": 32,
        "controlQueueBufferThreshold": 256,
        "controlQueueVisibilityTimeout": "00:05:00",
        "maxQueuePollingInterval": "00:00:30",
        "partitionCount": 4,
        "workItemQueueVisibilityTimeout": "00:05:00"
      },
      "tracing": {
        "traceInputsAndOutputs": false,
        "traceReplayEvents": false
      },
      "maxConcurrentActivityFunctions": 10,
      "maxConcurrentOrchestratorFunctions": 10,
      "extendedSessionsEnabled": false,
      "extendedSessionIdleTimeoutInSeconds": 30,
      "useGracefulShutdown": true,
      "useAppLease": true,
      "localRpcEndpointEnabled": true
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[2.*, 3.0.0)"
  }
}
```

Since the new Function App was behaving the exact same, I decided to remove most of the explicit config for the `durableTask` section and now the config looks like this and things appear to scale out correctly.

```
{
  "version": "2.0",
  "functionTimeout": "00:10:00",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    },
    "logLevel": {
      "Host.Triggers.DurableTask": "Warning",
      "Host.Aggregator": "Warning",
      "Host.Results": "Error",
      "Host.Startup": "Warning",
      "Host.Status": "Warning",
      "Host.LanguageWorkerConfig": "Warning",
      "Microsoft": "Warning",
      "Worker": "Warning",
      "DurableTask.Core": "Warning",
      "DurableTask.AzureStorage": "Warning",
      "DurableTask.DurableTaskListener": "Warning",
      "Function": "Warning"
    }
  },
  "extensions": {
    "durableTask": {
      "hubName": "startTests"
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[2.*, 3.0.0)"
  }
}
```

So...I'm guessing one of the settings I had defined was causing the Scale Out Controller to not behave correctly.  My gut tells me it was the `localRpcEndpointEnabled` setting or maybe the `useAppLease` setting.  I had disabled the `localRpcEndpointEnabled` setting due to some issues with the version 1.8.x Durable Task extension, but last night in troubleshooting, I upgrade to v2.4.1 so this setting was no longer needed.

**Comment by davidmrdavid** [comment]
Thank you for raising this issue @jawa-the-hutt. I've added this as an investigation for our upcoming sprint, which starts this Monday. On top of mind, I'm not too familiar with the scaling logic when interacting with KEDA but I'll sync with @cgillum who might be more familiar with that interaction, and the settings you bring up, and get back to you as soon as possible.

_Thanks!_
⚡ ⚡

**Comment by jawa-the-hutt** [comment]
@davidmrdavid - Thanks for getting in the upcoming sprint.  FWIW, I don't think KEDA is really a part of the overall issue, but wouldn't hurt to check.  I brought it up more to help make things more clear in terms of how we are using things and where the actual bulk of the CPU bound activity is happening.

With the `host.json` settings removed as I showed in the second example of it, things appear to be better, but not where they should be.  At this point, I can scale to 2 instances, but I can't get it to go above that at all.  For example:

![image](https://user-images.githubusercontent.com/1318561/106397362-96d8ba80-63d2-11eb-8e60-f8de03492402.png)

^^^^ here you can see that only two instances are running, but the following screenshot shows the workitems queue.  There are 55 in the queue in the screenshot and have been that way for several minutes. 

![image](https://user-images.githubusercontent.com/1318561/106397400-bb349700-63d2-11eb-8090-13325bb99536.png)

Please correct me if I've misunderstood how the scaling should work, but my understanding is that the Scaler Host will monitor (peek into) this queue and try and get as many of the messages out of it as possible as quickly as possible.  It will start adding instances on its own and then take the default amount (10x the # of vCPU's).  Since we're on a consumption plan, this is one vCPU so it will by default take 10 messages in the queue the next time it adds a host.  However, this is not happening....right now, I've basically got a queue depth of 20 and as one item finishes up it drops out the bottom and then another item is brought into the top.  

In reality, what I should have is a queue depth of 10 to start, and then the Scaler host should start adding instances until the queue depth is such that all messages are taken out of the workitem queue for processing.  So, if there are 100 items in the workitem queue to start, then I should have 10 instances going if I have understood how this is supposed to work correctly.  Again...please feel free to explain things differently if I've misunderstood.

**Comment by jawa-the-hutt** [comment]
@davidmrdavid  

I came across this [issue](https://github.com/Azure/azure-functions-durable-extension/issues/1470)   in the Durable Extensions repo and I think the issue I've been seeing is related to doing all this testing in a non-production slot.  I made a few configuration changes and was able to run against the production slot with what appear to be total success. 

Initially, there were 10 items taken out of the workitem queue and within 15-30 seconds every other message was taken out...or hidden rather as I think that's what actually happens underneath as the items are being processed.  The instances in the production slot also increased to take care of the items.

So, I think this item can be closed unless you feel otherwise.

**Comment by davidmrdavid** [comment]
Hi @jawa-the-hutt,
That's great to hear! Indeed, if the system is now scaling as expected then I think this is safe to close.

I'm also starting to think it might be useful to mark issues such as the one you linked with a special label that denotes that they document a "gotcha" when developing Durable Functions. I'll share with the rest of team to see what they think :)

Thanks again! I'll close this issue for now ⚡ ⚡
