### ISSUE TITLE
Nodejs Durable function distributed log enablement / correlation needed

### ISSUE THREAD

**Issue by MuhamedSalihSeyedIbrahim** [Azure/azure-functions-durable-js#256]
We are using Nodejs run time, azure durable function sdk v1.4.6 and application insight sdk v1.8.10.
we are logging traces across trigger , orchestrator (single) & activity function (many) but the traces are not correlated across as orchestrator and each of activity function start its own new operation or correlation id and loses it old one from trigger.

Read the article, https://tsuyoshiushio.medium.com/durable-functions-distributed-tracing-71426fe2246f similar feature expected by us is going to be in GA in C#.
likewise when can we expect it in nodejs.

Team Is there a way to correlate log across the (Durable functions) trigger , orchestrator and activity function in Nodejs application insight sdk/ some other way?

**Comment by davidmrdavid** [comment]
cc/ @bachuv do you know if this is something that's already working for C#?

**Comment by bachuv** [comment]
@davidmrdavid In C#, the client and activity function logs have the correlated `operationId`, but orchestrator logs have a different one ([#1805](https://github.com/Azure/azure-functions-durable-extension/issues/1805)). 

This issue seems a little different since client, orchestrator, and activity function logs all have different `operationId`s.

**Comment by davidmrdavid** [comment]
Thanks @bachuv!

Hi @MuhamedSalihSeyedIbrahim,

Thank you for reporting this bug. As you point out, we're currently focusing on stabilizing Distributing Tracing for C#, towards a GA release. As a result, I don't think we can give a concrete timeline on reaching GA for JavaScript but it's next on our list.

In the meantime, I suspect that using the OpenCensus Azure tooling here (https://docs.microsoft.com/en-us/javascript/api/overview/azure/core-tracing-readme?view=azure-node-preview) and using your orchestration's instanceID as a grouping key should allow you to correlate logs together. Do you mind giving it a try?

**Comment by MuhamedSalihSeyedIbrahim** [comment]
> Thanks @bachuv!
> 
> Hi @MuhamedSalihSeyedIbrahim,
> 
> Thank you for reporting this bug. As you point out, we're currently focusing on stabilizing Distributing Tracing for C#, towards a GA release. As a result, I don't think we can give a concrete timeline on reaching GA for JavaScript but it's next on our list.
> 
> In the meantime, I suspect that using the OpenCensus Azure tooling here (https://docs.microsoft.com/en-us/javascript/api/overview/azure/core-tracing-readme?view=azure-node-preview) and using your orchestration's instanceID as a grouping key should allow you to correlate logs together. Do you mind giving it a try?

Thanks for response @davidmrdavid, 

Yes Sure, I can try 👍.

Can I get some help/info, 
1.   Is there any core-trace lib sample implementation / examples? particularly for durable function scenario?
2.   want to know if its prod ready ?
3.   If it can be integrated to application insights(this will be great if it can some how push logs to application insights) ?
4.   want to know if it can work with azure application insights sdk?
5.   I just visited npm web page of azure core-trace node lib it have other azure sdk as dependency want to know if it support auto correlation and auto tracking of telemetry?

**Comment by davidmrdavid** [comment]
I'll get back to you on this, I'll spin up an internal thread to ask all these questions :)

**Comment by MuhamedSalihSeyedIbrahim** [comment]
@davidmrdavid thanks,
awaiting for your instructions.

**Comment by davidmrdavid** [comment]
Hi @MuhamedSalihSeyedIbrahim,

I asked internally for the right way to go about getting this correlated telemetry and I was pointed to this documentation: https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node?tabs=v2#log-custom-telemetry

In particular, this paragraph seems key to what you're trying to accomplish:
> The tagOverrides parameter sets the operation_Id to the function's invocation ID. This setting enables you to correlate all of the automatically generated and custom telemetry for a given function invocation.

As the rest of the "Log custom telemetry" section explains, this writes your traces to Application Insights. I also don't see anything indicating that this is not GA, but I'm not part of the owner team for that feature so I can't speak to that with authority.

**Comment by MuhamedSalihSeyedIbrahim** [comment]
@davidmrdavid -

I am already using this tag overrides in http API flows up to some extent.

But here in durable functions. The problem I face is,
context (context.traceContext.traceparent) is freshly generated in orchestrator and activity functions therefore if I use that to correlating (using tag override) still its broken **due to trigger , orchestrator and all activities has it own freshly generated operation id** 

Want to know if there is a way that I can use to share this same operation id among execution of  trigger , orchestrator and all activities of same flow?

**Comment by MuhamedSalihSeyedIbrahim** [comment]
@davidmrdavid, That's instantaneous response, Great idea.
No, passing instance id to activity's input may not be necessary as orchestrator and all its activities share same instanceID. 
Atleast I have observed that but still
I have small question, Do orchestrator and activity differ in its instanceId when it comes to same flow?

 I shall try this approach and let you know ,if my issue is resolved.

**Comment by davidmrdavid** [comment]
Good to hear @MuhamedSalihSeyedIbrahim! Generally speaking, I don't expect activities to be able to access the instanceID of their parent orchestrator without manually passing that value as input. However, if you're able to show otherwise, then I'd love to know! Looking forward to your update :)

**Comment by MuhamedSalihSeyedIbrahim** [comment]
@davidmrdavid Sorry for late reply,
I have observed that context.bindingData.instanceId is same and is present in both activities and orchestrator

It worked fine upto some extent, I can take it as temp soln till the e2e durable function log/ trace feature is complete and out

**Comment by MuhamedSalihSeyedIbrahim** [comment]
If possible and you have any idea about how to use core-trace azure lib lit me up,I can try that lib too if good amount of sample and docs is available for it

**Comment by davidmrdavid** [comment]
Thanks @MuhamedSalihSeyedIbrahim for the update. Until the Durable-aware correlation tracing feature is fully ready, I think we'll have to rely on this temporary workaround but we're making rapid progress on this front. I'll definitely reach out if alternative workarounds come my way 😄 . In the meantime, I'll close this thread as resolved and we'll continue working on improving distributed tracing on our end. Thanks!

**Comment by MuhamedSalihSeyedIbrahim** [comment]
@davidmrdavid @bachuv any update team😅
