### ISSUE TITLE
Upgrade Azure durable functions from 1.6.2 to 1.7.0 

### ISSUE THREAD

**Issue by nafis00141** [Azure/azure-functions-durable-js#26]
I have written some durable functions using version 1.6.2 . The new [1.7.0](https://github.com/Azure/azure-functions-durable-extension/releases) is now out. I want to upgrade.

Will just doing  `func extensions install -p Microsoft.Azure.WebJobs.Extensions.DurableTask -v 1.7.0` do the job? or do I need to do something else?

**Comment by kashimiz** [comment]
Running `func extensions install -p Microsoft.Azure.WebJobs.Extensions.DurableTask -v 1.7.0` from the root of your function app's folder structure and deploying your changes should be the only step needed to upgrade, unless you're running a 0.0.* version of the `durable-functions` npm package. If you are, you'll need to upgrade to version 1.0.0.
