### ISSUE TITLE
typedoc as a dependency instead of a dev-dependency

### ISSUE THREAD

**Issue by sijucm** [Azure/azure-functions-durable-js#261]
Why is typedoc listed as a dependency instead of a dev-dependency? Is it really required?

I'm facing an issues that in my corporate they use NexuIQ and there is an issue in the shelljs dependency used by typedoc. I wonder if it is possible not to use typedoc. https://github.com/shelljs/shelljs/issues/945

**Comment by davidmrdavid** [comment]
Hi @sijucm,

Thank you for reaching out! I also believe typedoc should only be necessary as a dev-dependency but I would have to do some validation first. The earliest I could push a new version of the JS package, with a potential swap of typedoc as a dev-dependency, would be this Friday, would that work for you all?

**Comment by beyerleinf** [comment]
Hi @davidmrdavid,

would be great to get this issue resolved since `typedoc` now depends on a vulnerable version of `marked` (see [TypeStrong/typedoc#1847](https://github.com/TypeStrong/typedoc/issues/1847)). Thanks!

**Comment by davidmrdavid** [comment]
Thanks for the ping @beyerleinf. We're actually planning to release a new JS package, specifically to remove warnings from `npm audit` sometime in the next few days. I'll make a note to also move this dependency. Thanks!

**Comment by davidmrdavid** [comment]
Closing as it's been resolved
