### ISSUE TITLE
How to notify client of state change in durable entity

### ISSUE THREAD

**Issue by jakobpn** [Azure/azure-functions-durable-js#277]
Is there a way that a durable entity can notify a client of a state change? 

For a prototype I would want a PowerPoint add-in to "wake up" and do some work every time an Excel add-in change the state of a durable entity. 

I assume that having the PowerPoint add-in poll the durable entity every 10-20 secs is not the way to go (unless I am willing to pay the compute bill and wait 10-20 secs for the PowerPoint add-in to "wake up").

**Comment by davidmrdavid** [comment]
@ConnorMcMahon, do we have a way to do this in C#?

**Comment by ConnorMcMahon** [comment]
So in general, there are two main ways for clients to receive updates from an endpoint.

1. Polling
2. The client sends a webhook URL to the server, and the server will post all future events to that webhook to notify the client.

Polling is the simple way to do this, but it is expensive for both the client and the server on the compute side of things.

Webhooks work great, but they require additional work on both the server and the client. The server needs to have webhook support, and the client needs to be able to support listening to an HTTP endpoint that it can give to the server.

In general, there is nothing stopping you from implementing the webhook pattern on a Durable Entity. You would just add a "RegisterWebhookUrl" operation that adds the URL to a list of URLs to send status updates too, and then just send updates to those endpoints when operations that update the state components that you care about.

The main limitation is if your client supports listening at a URI, and I am not familiar enough with PowerPoint add-ins to say whether this is an option.
