### ISSUE TITLE
Non-Deterministic workflow detected when using for loop in orchestrator

### ISSUE THREAD

**Issue by stefancosquer** [Azure/azure-functions-durable-js#295]
### Description

I'm trying to call a set of activity functions from my orchestrator inside a for loop, but it always fails silently after the same amount of loops (413), with this message : `Non-Deterministic workflow detected: TaskScheduledEvent: 2 TaskScheduled noop`

Last message in logs (don't know if it helps) : `Function 'orchestrator (Orchestrator)' awaited. IsReplay: False. State: Awaited. HubName: DurableFunctionsHub. AppName: . SlotName: . ExtensionVersion: 2.5.1. SequenceNumber: 1009.`

### Expected behavior
The orchestrator should succeed.

### Actual behavior
The orchestrator fails after 413 loops (always the same count).

### Relevant source code snippets

Here is a simple code example to reproduce the problem.

Orchestrator code

```typescript
export default orchestrator(function* (context) {
    context.df.setCustomStatus({ progress: { current: 0, total: 1000 } });
    for (let index = 0; index < 1000; index++) {
      context.df.setCustomStatus({ progress: { current: index, total: 1000 } });
      yield context.df.callActivity('noop');
    }
}
```

Activity code

```typescript
export const index = async () => {};
```

### Known workarounds

I tried to change Durable Functions extension version (2.4.x), upgraded Azure Functions Core Tools from 3.x to 4.x, modified parameters in `host.json` file (Task Hub name), purged instance history, without any luck.

### App Details

- **Durable Functions extension version**: 2.5.1
- **Azure Functions runtime version**: 2.0
- **Programming language used**: Javascript

**Comment by davidmrdavid** [comment]
Hi @stefancosquer,

Apologies for the late response. I just tried reproducing this and my orchestrator seems to be on its way to completing (current iteration is 545). Are you still experiencing this?

If so, could you please attach a `.zip`'ed reproducer?

Also, are you able to reproduce this even when you make your Activity Function explicitly return a value? Thanks!
