### ISSUE TITLE
Any plans to support node v.16?

### ISSUE THREAD

**Issue by ntodorov** [Azure/azure-functions-durable-js#296]
Any plans to support node v.16?

**Comment by anthonychu** [comment]
Node.js 16 support was [recently added](https://azure.microsoft.com/updates/public-preview-nodejs-16-in-azure-functions/) to Azure Functions in public preview. Durable Functions works with it. Ensure you are using Azure Functions v4.

**Comment by davidmrdavid** [comment]
Thanks for chiming in, Anthony! I'll be closing this thread since it's been answered, thanks!
