### ISSUE TITLE
Azure Durable function get stuck in 'Running' state sometimes

### ISSUE THREAD

**Issue by dozienwankwoh** [Azure/azure-functions-durable-js#307]
Describe the bug
Azure HTTPs durable function will complete as normal then suddenly it gets starts getting stuck in running state. Some Observations:

- This issue happens intermittently and I cannot replicate it. 
- Once an execution gets stuck in running status, every subsequent execution gets stuck in running. 
     - Sometimes the function will operate normally again after a restart. 
     - Sometime the function will operate normally again after switching deployment (All deployment slots have same code) 
- Application Insight logs show that an activity functions throws a timeout error eventually. This activity function is not async and it uses promises. 

The durable function will be working just fine, and then suddenly it will start getting hung up at "runTimeStatus: Running" with no code changes or config changes.

Investigative information

Durable Functions extension version: "[2.*, 3.0.0)"
durable-functions npm module version: "^1.5.3"
Language (JavaScript/TypeScript) and version: js
Node.js version: 14
If deployed to Azure App Service

Timestamp: 2022-01-14T11:32:05.01Z
Function App name: (InvocationID) 28eb24ae-1c48-4f16-baba-baa444c3c85f
Region: South Central US

If you don't want to share your Function App name or Functions names on GitHub, please be sure to provide your Invocation ID, Timestamp, and Region - we can use this to look up your Function App/Function. Provide an invocation id per Function. See the Functions Host wiki for more details.

To Reproduce

Go to '...'
Click on '....'
Scroll down to '....'
See error
While not required, providing your orchestrator's source code in anonymized form is often very helpful when investigating unexpected orchestrator behavior.

Expected behavior
Function completion

Actual behavior
Function stuck in "runtimeStatus": "Running" state sometimes

Additional context

Development environment (ex. Visual Studio)
Links to source
Additional bindings used
Function invocation IDs

**Comment by davidmrdavid** [comment]
Hi @dozienwankwoh,

Thanks for reaching out, and apologies for the late response. I had a few questions:

1. When did this issue _start_ happening?
2. When you say that the function works normally after switching the deployment slot, do you mean that there's one slot where the issue never occurs?
3. Can you clarify what you meant by "This activity is not async and it uses promises"? In particular, can you describe how promises are being used here?
4. When you say that the app will get "hung up", do you mean that it gets stuck in the middle of an orchestration, or that new orchestrations won't start?
5. Can you give me a description of what your orchestration does, and a rough idea of the order in which it invokes Durable Functions APIs? Pseudocode would be helpful here.
6. Can you provide me with your application name and multiple start and end timestamps (a time range) of when this issue occurred?

Thanks!
