### ISSUE TITLE
Support DurableOrchestrationContext.GetGUID

### ISSUE THREAD

**Issue by kashimiz** [Azure/azure-functions-durable-js#31]
`DurableOrchestrationContext` should support the `getGUID` method to deterministically generate GUIDs as documented [here](https://azure.github.io/azure-functions-durable-extension/api/Microsoft.Azure.WebJobs.DurableOrchestrationContext.html#Microsoft_Azure_WebJobs_DurableOrchestrationContext_NewGuid). This will require work on the extension side.

**Comment by cgillum** [comment]
A more efficient alternative would be to implement it directly in JavaScript. The `uuid` library already supports this: https://github.com/kelektiv/node-uuid#readme (search for `uuidv5`).
