### ISSUE TITLE
Fetching Status of Running Orchestrator Temporarily Returns Custom Status From Previously Ran Orchestrator

### ISSUE THREAD

**Issue by AKtroske** [Azure/azure-functions-durable-js#317]
**Describe the bug**
We have an http triggered function that starts a single orchestrator which calls a few activity functions in parallel (see code snippet below). We use statusQueryGetUri provided by the subsequent client to monitor said orchestrator and have encountered some odd results-- for a moment, the orchestrator will show a runtime status of "Running" while displaying the custom status of a previously completed orchestrator.  However, when it completes (runtimeStatus === 'Completed'), it shows us the expected response. This behavior occurred on a fairly consistent basis when running the orchestrator sequentially with a relatively short period of time in between each call (a few seconds?). The length of time that the statusQueryGetUri will show the previous custom status has been inconsistent, if even relevant.

**Investigative information**

- Durable Functions extension version: 2.4.3
- durable-functions npm module version: 1.4.6
- Language (JavaScript/TypeScript) and version: JS
- Node.js version: ~12

***If deployed to Azure App Service***

- Timeframe issue observed: 1/27-present
- Function App name: cm-service-dev-ldh245mnpybje
- Function name(s): bulkSendDirectMethod
- Region: USW
- Orchestration instance ID(s): 7a8ffd871ec64626b09e8d4bef3984c0

**To Reproduce**

1. Trigger orchestrator via http request a few times
2. Query the statusQueryGetUri periodically so as to catch it before completion

***Representative Code Sample***
```js
function* sampleF(context, customStatusManager) {
    try {
        const { devices, method, payload, validation } = input;
        customStatusManager.setSendingStatus(`Attempting to send ${method} to ${devices.join(', ')}`);
        const dmTasks = devices.map((deviceId) => context.df.callActivity('dfActivity_sendDirectMethodToDevice', {
            device_id: deviceId,
            method,
            payload,
        }));
        const results = yield context.df.Task.all(dmTasks);
        customStatusManager.setSendingStatus(`${method} command sent successfully`);
        if (validation) {
          // calls activity that validates results
        }
        customStatusManager.setCompletedStatus(`${method} command sent successfully`, results);
        return customStatusManager.genStatus('completed', SUCCESS_MSG, results);
    } catch (err) {
        return customStatusManager.setError(err.message);
    }
}
```

**Expected behavior**
The status response should not show the custom status of a previously completed orchestrator and instead the show custom status of the current orchestrator.

**Actual behavior**
Previous orchestrator custom status' will be shown while orchestrator runtime status is "running" and then will show expected response when it finally completes.

**Screenshots**

A screenshot of the postman response from querying the statusGetQueryUri showing the "Running" runtime status with the custom status of a previously completed orchestration (about 5 runs prior, and as shown by the timestamps generated from the activity functions, about 13 minutes prior -- previous request in SS2)

**SS1**
![oldDataShown1SS](https://user-images.githubusercontent.com/43590455/152264223-6082af36-cb78-4429-afb3-c5956e123590.PNG)

Here is the original response from the request I am referring to above. As you can see one of the methods actually failed in this custom status, which is easily spotted in the custom status of SS1

**SS2**
![fiveRequestsEarlierOldDataFileSS](https://user-images.githubusercontent.com/43590455/152264591-5b27fc43-9f89-449b-9595-2dd320d897de.PNG)

Here is the final result. Notice the custom status has changed to look as expected and same orchestration Id as SS1

**SS3**
![newDataShownSameStatusReqSSCropped](https://user-images.githubusercontent.com/43590455/152264781-1ef87f44-ff23-4e72-8c27-b71ad9940ee8.png)

**Known workarounds**
We ending up toying around with a few things, but the main change that **seemed* to eliminate the issue was adding a unique ID to the input of the activity calls for 'dfActivity_sendDirectMethodToDevice'. We had a hunch that somehow the status was picking up information just based on activity name and input, which would have been the same for all of these sequential orchestrations. 

The activity call ended up just looking like this:
```js
const dmTasks = devices.map((deviceId) => context.df.callActivity('dfActivity_sendDirectMethodToDevice', {
  device_id: deviceId,
  method,
  payload,
  activityId: helper.getUniqueId(),
}));
```

*We ran this about 10-20 times manually and were not able to reproduce the previous behavior once, where we would normally have seen it several time prior to this change.

**Additional note**
Another side note, when we were debugging this, we did check the orchestration history table and found that it was recording the expected responses from the activity functions, even though the status response was showing something else. This is how we knew that the final response, when the runtime status was "Completed", was the right one.

**Comment by AKtroske** [comment]
bump

**Comment by lilyjma** [comment]
Hi @AKtroske - sorry for the delayed response. Could you try upgrading the Durable Functions extension to see if that will fix the issue?
