### ISSUE TITLE
Function does not return expected value, sometimes (returning old data?)

### ISSUE THREAD

**Issue by hanvyj** [Azure/azure-functions-durable-js#32]
I'm getting some really odd behaviour with a function. I had the function return some test output earlier in development, and now it's "stuck" returning that output. Sometimes. Seems half the time it returns the expeced output (what's currently in the code), half the time it retuns some old (cached?) output that no longer exists anywhere in my project.

The client/orchestrator is designed to take a function name as an input and run that single function (it's for testing and developing functions in isolation!). It's triggered from a HTTP call eg: `http://localhost:7071/api/integration-test/my-function-name` and returns the function ID for tracking etc:

### test-client
function.json:
```
{
  "bindings": [
    {
      "authLevel": "anonymous",
      "name": "req",
      "type": "httpTrigger",
      "direction": "in",
      "route": "integration-test/{functionName}",
      "methods": ["post"]
    },
    {
      "name": "$return",
      "type": "http",
      "direction": "out"
    },
    {
      "name": "starter",
      "type": "orchestrationClient",
      "direction": "out"
    }
  ]
}
```
index.ts
```
export async function run(context: Context, req: HttpRequest): Promise<any> {
  if (!(req.params && req.params.functionName)) {
    return {
      body: `No specified function name in params`,
      status: HttpStatusCode.BadRequest
    };
  }

  const id = uuid();

  const startArgs = [
    {
      FunctionName: "test-orchestrator",
      Input: {
        testFunction: req.params.functionName,
        testInput: req.body
      },
      InstanceId: id
    }
  ];

  context.bindings.starter = startArgs;

  return {
    body: id,
    status: HttpStatusCode.OK
  };
}
```

### test-orchestrator
The `test-orchestrator` function takes that input, kicks off the function that it has been passed:

function.json
```
{
    "disabled": false,
    "bindings": [
      {
        "type": "orchestrationTrigger",
        "name": "context",
        "direction": "in"
      }
    ]
  }
```
index.ts:
```
module.exports = orchestrator(function*(context) {
  AzureLoggingContext.getInstance().addContext(context);

  const input = context.df.getInput();

  return yield context.df.callActivity(
    input.testFunction,
    input.testInput
  );
});
```
### my-function-name
Now, the function I'm trying to test has been taken back to something stupidly simple:
function.json
```
{
  "disabled": false,
  "bindings": [
    {
      "name": "input",
      "type": "activityTrigger",
      "direction": "in"
    }
  ]
}
```
index.ts
```
export async function run(context: Context, input: { keyValuePairs: any, mapTemplateConfigurationId: string }): Promise<any> {
  context.log!("Mapping with input " + JSON.stringify(input));
  return { test: "test" };
}
```
It just retuns `{ test: "test" }`. However, at some point in the past it returned some placeholder data: `{"key":"???","kind":"Alert","ou":"???","type":"ENTITY","attributes":[]}`.

This is the DurableFunctionsHubInstances from the storage tables:

|PartitionKey|Timestamp|ExecutionId|Input|Name|Output|
|-|-|-|-|-|-|
|efa9d520-fe00-11e8-bc5e-35e09dcfee36|2018-12-12T11:28:03.753Z|d6c907b0b28c49789c1d0a2990e4d47e|{"testFunction":"my-function-name","testInput":{"keyValuePairs":"test","mapTemplateConfigurationId":"test"}}|test-orchestrator|{"test":"test"}|
|33052e00-fe01-11e8-bc5e-35e09dcfee36|2018-12-12T11:29:58.673Z|abc756ba41fe447b8f83dfff3fb0c07e|{"testFunction":"my-function-name","testInput":{"keyValuePairs":"test","mapTemplateConfigurationId":"test"}}|test-orchestrator|{"test":"test"}|
|6824e170-fe01-11e8-bc5e-35e09dcfee36|2018-12-12T11:31:12.692Z|9fe6ae3f761445778aab9fd8de64e471|{"testFunction":"my-function-name","testInput":{"keyValuePairs":"test","mapTemplateConfigurationId":"test"}}|test-orchestrator|{"test":"test"}|
|87d202f0-fe01-11e8-bc5e-35e09dcfee36|2018-12-12T11:32:09.961Z|fd45a3af4d404eceb786fea6796259b0|{"testFunction":"my-function-name","testInput":{"keyValuePairs":"test","mapTemplateConfigurationId":"test"}}|test-orchestrator|{"key":"???","kind":"Alert","ou":"???","type":"ENTITY","attributes":[]}|

Every time I call the function there's a chance it works and returns the current function implementation. But randomly it just returns some old output. A filesearch on my code results in no occurances of this data.

**Comment by hanvyj** [comment]
I renamed the function "my-function-name2" and it worked for a while, but now again it's started not running the actual function. The orchestrator runs, but I never get any console output from the "my-function-name2" function - it just returns with some old value.

**Comment by kashimiz** [comment]
That's an interesting situation; I'm sorry you're experiencing these issues. Can you provide some more information about your system?

- the installed version of the `durable-functions` npm package
- the installed version of the Microsoft.Azure.WebJobs.Extensions.DurableTask extension (see `extensions.csproj`
- the version of TypeScript you're using

I'm also curious what a problematic orchestration's history table entries look like; seeing that would help isolate the problem.

@cgillum Have you encountered any cases like this in .NET Durable Functions?

**Comment by hanvyj** [comment]
> That's an interesting situation; I'm sorry you're experiencing these issues. Can you provide some more information about your system?
> 
> * the installed version of the `durable-functions` npm package
> * the installed version of the Microsoft.Azure.WebJobs.Extensions.DurableTask extension (see `extensions.csproj`
> * the version of TypeScript you're using
> 
> I'm also curious what a problematic orchestration's history table entries look like; seeing that would help isolate the problem.
> 
> @cgillum Have you encountered any cases like this in .NET Durable Functions?

This was with version durable-functions 1.0.0 DurableTask version=1.6.2. Typescript version 3.1.6.

I updated yesterday to the latest version (1.1.2 and 1.7.0) and I haven't seen it returning old data. Instead (with about the same frequendcy) it seems instead to get stuck in the "Pending" state indefinately, and never starts the function:

|PartitionKey|Timestamp|ExecutionId|Input|Name|RuntimeStatus|Version|Output|
|-|-|-|-|-|-|-|-|
|101cf860-fe46-11e8-8c77-4391fac92b0c|2018-12-12T19:42:31.792Z|47a5d7039c3d4a54a9ae57be4052788e|{"testFunction":"my-function-name","testInput":{...}|test-orchestrator|Completed|{…}|
|b5f861c0-fe46-11e8-bae0-fd52697ababf|2018-12-12T19:47:09.341Z||{"testFunction":"my-function-name","testInput":{...}|test-orchestrator|Pending||
|2350ef80-fe47-11e8-a539-b32d7e0e26cd|2018-12-12T19:50:13.637Z|2cb3c181908f40df98fa616865627785|{"testFunction":"my-function-name","testInput":{...}|test-orchestrator|Completed|{…}
|6bfca520-fe48-11e8-ae6b-ab9a71674545|2018-12-12T19:59:24.134Z||{"testFunction":"my-function-name","testInput":{...}|test-orchestrator|Pending||
|c71303e0-fe49-11e8-9c75-fb01827f4b68|2018-12-12T20:09:06.475Z||{"testFunction":"my-function-name","testInput":{...}|test-orchestrator|Pending||
|2e20d9e0-fe4a-11e8-a388-6fc03dab9d8a|2018-12-12T20:12:00.233Z|f9a32d9a598840779a85c485a5b7e0bc|{"testFunction":"my-function-name","testInput":{...}|test-orchestrator|Completed|{…}
|4f8a51f0-feb9-11e8-9dd8-d7b7ff3d49ea|2018-12-13T09:27:32.532Z|693b99000e22485ebb61d96f018b450f|{"testFunction":"my-function-name","testInput":{...}|test-orchestrator|Completed|{…}
|6133f500-feb9-11e8-9dd8-d7b7ff3d49ea|2018-12-13T09:27:59.008Z||{"testFunction":"my-function-name","testInput":{...}|test-orchestrator|Pending||

Left one running for over an hour now.

**Comment by cgillum** [comment]
@hanvyj do you have any messages in your Azure queues?

If not, is it possible that the storage account you're using might also be in use by another function app running somewhere else?  One way to rule out any conflicts with other apps is to configure a unique task hub name in your host.json, like this:

```json
{
  "version": "2.0",
  "extensions": {
    "durableTask": {
      "HubName": "MyTaskHub123"
    }
  }
}
```

Also, what platform are you running on (Windows, macOS, Linux)?

**Comment by hanvyj** [comment]
It's very possible it was running another function app, or some older version of this one. I deleted the contanier and restarted it and it seems to have resolved. If it happens again I'll try give them a task name.

But it seems to be resolved!

**Comment by cgillum** [comment]
@hanvyj 

> Would running the app (locally) on two different machines pointing at the same storage cause these issues?

Yes, it definitely will. Both the local app and the Azure-deployed app will be competing for the same messages.

I understand that it can be a pain to manage the task hub names. It was a poor design choice to default to a static name and I regret it quite a bit. One thing you can try to reduce the pain is to use unique app settings/environment variable to assign the names rather than hard-coding it into host.json. That might be easier to maintain since you don't actually have to change your function app contents. Details and an example of how to do this can be found here: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-task-hubs#hostjson-functions-2x-1

**host.json**
```json
{
  "version": "2.0",
  "extensions": {
    "durableTask": {
      "HubName": "%MyTaskHub%"
    }
  }
}
```

**local.settings.json** (for local development - for production use app settings / environment variables):
```json
{
  "IsEncrypted": false,
  "Values": {
    "MyTaskHub" : "samplehubname"
  }
}
```

**Comment by hanvyj** [comment]
That should work fine for development having things in local settings, thanks a lot!

**Comment by cgillum** [comment]
Great! I'll close this issue for now. Do let us know if you run into additional issues.
