### ISSUE TITLE
Non-Deterministic workflow detected when using for loop in orchestrator

### ISSUE THREAD

**Issue by Eddynsonvega** [Azure/azure-functions-durable-js#324]
**Describe the bug**
I'm calling an activity function from my orchestrator within a for loop, but it always fails silently after a number of loops, with this message: **_Non-Deterministic workflow detected: TaskScheduledEvent: 1844 TaskScheduled getdata_**
@davidmrdavid 

**Investigative information**

- Durable Functions extension version: 2.0
- durable-functions npm module version: 3.7
- Language (JavaScript/TypeScript) and version: Python
- Node.js version: 3.7

***If deployed to Azure App Service***

- Timeframe issue observed:
- Function App name: func-getdataion-prod-001
- Function name(s): Fields_dlidSequence
- Region: East US 2
- Orchestration instance ID(s): d4c95688bc29f62c61718e2d75143b72

**Expected behavior**
The orchestrator should succeed.

**Actual behavior**
El orquestador falla después de 3.587 bucles.

**Screenshots**
![image](https://user-images.githubusercontent.com/33761061/156764522-a3530f75-11e7-4138-b0f7-3610b8c916bf.png)

**Comment by davidmrdavid** [comment]
Hi @Eddynsonvega, thank you for reaching out and apologies for my late response - I was out of office until just recently.

Is this issue still ongoing? I just took a brief look at your application logs for the last 3 days and couldn't find any errors? If the issue continues, can you please give me the latest timestamps of when this issue occurred? Thanks!
