### ISSUE TITLE
context.df.callHttp POST calls body not recognized

### ISSUE THREAD

**Issue by DanelGorgan** [Azure/azure-functions-durable-js#349]
**Describe the bug**
Errors on POST requests using context.df.callHttp. For this purpose, i used https://api.thecatapi.com/v1/votes in order to test the function.
The code looks as the following and is triggered from an orchestrator function:
`
const response = yield context.df.callHttp("POST", 'https://api.thecatapi.com/v1/votes', {
                    "image_id": "asf2",
                    "sub_id": "my-user-1234",
                    "value": 1
                  })
`
The received response: `content:'{"message":"\\"image_id\\" is required","status":400,"level":"info"}'`

In the documentation, the third parameter is content?: string | object, which in my case is specified as an object. I also tried with other APIs and I've got the same result.

The tests were done local using Visual Studio and Azure Functions extension.
**Investigative information**

- durable-functions npm module version: 1.5.4
- Language (JavaScript/TypeScript) and version: Typescript 4.0.0
- Node.js version: 14.9

Is there anything I'm missing? Thank you.

**Comment by davidmrdavid** [comment]
Thanks for reaching out @DanelGorgan! It would help me accelerate the investigation if you could attach a reproducer (just don't include any secret string in it) to this thread :) . That way I can make sure I'm working with the same code as you are. Please let me know if that's possible, it'll make it easier to debug. Thanks!

**Comment by DanelGorgan** [comment]
Hi David,
Thanks for reaching out! 
I extracted the call into a much simpler code where the error still persists.

DurableFunctionsHttpStart1:

> import * as df from "durable-functions"
> import { AzureFunction, Context, HttpRequest } from "@azure/functions"
> 
> const httpStart: AzureFunction = async function (context: Context, req: HttpRequest): Promise<any> {
>     const client = df.getClient(context);
>     const instanceId = await client.startNew(req.params.functionName, undefined, req.body);
> 
>     context.log(`Started orchestration with ID = '${instanceId}'.`);
> 
>     return client.createCheckStatusResponse(context.bindingData.req, instanceId);
> };
> 
> export default httpStart;

DurableFunctionsOrchestratorJS1:

> import * as df from "durable-functions"
> 
> const orchestrator = df.orchestrator(function* (context) {
>     const response = yield context.df.callHttp(
>         "POST",
>         'https://api.thecatapi.com/v1/votes',
>         { "image_id": "asf2", "sub_id": "my-user-1234", "value": 1 }
>     );
> 
>     context.log(response);
> 
> });
> 
> export default orchestrator;

  "dependencies": {
    "durable-functions": "^1.5.4"
  },
  "devDependencies": {
    "@azure/functions": "^3.0.0",
    "typescript": "^4.0.0"
  }

I am testing it locally using http://localhost:7071/api/orchestrators/DurableFunctionsOrchestratorJS1.

Is there a documentation regarding on how the content parameter should look like (and maybe all the other parameters)? Or examples?  Thank you.

**Comment by davidmrdavid** [comment]
Thanks @DanelGorgan.

I got this to work by adding `header` values for the API key and the content-type.

Can you please try with the following orchestrator?

```TypeScript
import * as df from "durable-functions"

const orchestrator = df.orchestrator(function* (context) {
const response = yield context.df.callHttp(
"POST",
'https://api.thecatapi.com/v1/votes',
{ "image_id": "asf2", "sub_id": "my-user-1234", "value": 1 },
{"x-api-key": "DEMO-API-KEY", "Content-Type": "application/json"}
);

context.log(response.content);
});

export default orchestrator;
```

For me this outputs

```
Functions:

        DurableFunctionsHttpStart: [POST,GET] http://localhost:7071/api/orchestrators/{functionName}

        DurableFunctionsOrchestratorJS: orchestrationTrigger

        Hello: activityTrigger

For detailed output, run func with --verbose flag.
[2022-04-25T22:27:30.660Z] Worker process started and initialized.
[2022-04-25T22:27:32.394Z] Executing 'Functions.DurableFunctionsHttpStart' (Reason='This function was programmatically called via the host APIs.', Id=40d6132b-2ab4-4a46-b28f-4980afec26f7)
[2022-04-25T22:27:32.604Z] Started orchestration with ID = 'f39c0ea1bcf14326b42cf950c1fa0298'.
[2022-04-25T22:27:32.679Z] Executed 'Functions.DurableFunctionsHttpStart' (Succeeded, Id=40d6132b-2ab4-4a46-b28f-4980afec26f7, Duration=320ms)
[2022-04-25T22:27:32.695Z] Executing 'Functions.DurableFunctionsOrchestratorJS' (Reason='(null)', Id=9b165a0a-5a54-4802-909f-dc1f6a9414b3)
[2022-04-25T22:27:32.759Z] Executed 'Functions.DurableFunctionsOrchestratorJS' (Succeeded, Id=9b165a0a-5a54-4802-909f-dc1f6a9414b3, Duration=68ms)
[2022-04-25T22:27:33.269Z] Executing 'Functions.DurableFunctionsOrchestratorJS' (Reason='(null)', Id=53e93720-a1fa-4fcd-a4b5-ec7e7b4cab7e)
[2022-04-25T22:27:33.283Z] {"message":"SUCCESS","id":526441}
[2022-04-25T22:27:33.303Z] Executed 'Functions.DurableFunctionsOrchestratorJS' (Succeeded, Id=53e93720-a1fa-4fcd-a4b5-ec7e7b4cab7e, Duration=37ms)
[2022-04-25T22:27:35.240Z] Host lock lease acquired by instance ID '000000000000000000000000135D7DF1'.
```

Thanks!

**Comment by DanelGorgan** [comment]
Hi @davidmrdavid ,
The problem was indeed that I didn't specified content-type header as json. I assumed it automatically detects the payload as in axios case (which I successfully created an activity function and made the request work).

As a closing question, besides https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-http-features?tabs=javascript#limitations are there any other advantages / disadvantages regarding using this approach vs activity functions with axios (maybe maximum parallel calls or any other concerns that might intrerupt the request)? Can we also set options like increasing timeout? Thank you.

**Comment by davidmrdavid** [comment]
Hi @DanelGorgan, glad to hear you're able to get this working now!

I believe the documentation you shared is the only resource we have describing the pros and cons of using the built-in HTTP API. I haven't done a deep dive investigating the performance implications of one  or the other, but I think it's safe to say that any advanced scenarios are best deferred to a native HTTP client like `axios`. 

When you talk about increasing the timeout, are you talking about the built-in HTTP API? If so, I don't think this is possible _yet_, but it may be possible once we complete [this](https://github.com/Azure/azure-functions-durable-extension/issues/1984) workitem to support [HttpRetryOptions](https://github.com/Azure/azure-functions-durable-extension/issues/1984).

**Comment by DanelGorgan** [comment]
Thanks David for the detailed explanations!
