### ISSUE TITLE
custom Orchestration status returns null. 

### ISSUE THREAD

**Issue by sckelly** [Azure/azure-functions-durable-js#35]
Documentation found here: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-custom-orchestration-status

Is incorrect.
Running the OrchestratorFunction I am getting a null error :

```
System.Private.CoreLib: Exception while executing function: Functions.HttpStart. System.Private.CoreLib: Result: Failure
Exception: TypeError: Cannot read property 'toString' of null
Stack: TypeError: Cannot read property 'toString' of null
    at module.exports (C:\Users\scott.kelly\Documents\git\durable-function-apps\HttpStart\index.js:13:52)
    at process._tickCallback (internal/process/next_tick.js:68:7).
```
I imagine this is because customStatus is not set initially in the Orchestrator and so has a null status.

Should also be noted in the listed example above for Javascript, the lines:
```
let durableOrchestrationStatus = await client.getStatus(instanceId);
    while (status.customStatus.toString() !== "London") {
```
are inconsistent. The example documentation is running a while loop on "status", which is never declared nor defined? It seems that the while loop should be running on "durableOrchestrationStatus.customStatus"..

I have attempted to fix null issue by running a while on the value and breaking when it is not null, however this sets off an infinite loop..
I have also attempted to set customStatus on orchestrator initialisation, but nothing updates.

Will keep attempting fixes, but clarification would be helpful.

**Comment by sckelly** [comment]
so far I have gotten around the null issue by running a polling check on customStatus == null, similar to the examples check on 'London'.

This could be closed if the null value is expected behaviour, however doc should be updated for misnamed variable :smile_cat:

**Comment by jeffhollan** [comment]
Thanks a ton @sckelly - makes sense. Closing this now and can track for docs issues
