### ISSUE TITLE
Limit amount of type (`d.ts`) files exposed to users

### ISSUE THREAD

**Issue by davidmrdavid** [Azure/azure-functions-durable-js#352]
After a discussion with @ejizba, we've learned that our TS project exports type-declaration files even for our internal utility files. This is problematic because it increases the type-management burden of our end users, and makes it inconvenient for us to import and reference external types in our project.

We should look to limit our exported `*.d.ts` files to include only public types.

**Comment by davidmrdavid** [comment]
FYI @hossam-nasr

**Comment by hossam-nasr** [comment]
Closed by #470
