### ISSUE TITLE
A running durable task is not scheduling after terminated on a draining node (platform scaling down) and rescheduled on another node 

### ISSUE THREAD

**Issue by chanyk-joseph** [Azure/azure-functions-durable-js#364]
**Describe the bug**
The incident is discovered during investigation of a random issue (**Support request ID**: 2205170030001127).

During the incident period, although the durable job shows "Running" runtimeStatus, the underlying logic is not running.

https://media-monitor-jobs-scheduler-durable-func-app.azurewebsites.net/runtime/webhooks/durabletask/instances/c07d27ac11804a9e885998bda93d736e?taskHub=mediamonitorjobsschedulerdurablefuncapp&connection=Storage&code=xxxxxxxxxxxxxxxxxxxxxx
Response:
```
{
    "name": "job",
    "instanceId": "c07d27ac11804a9e885998bda93d736e",
    "runtimeStatus": "Running",
    "input": {
         ....
    },
    "customStatus": "RUNNING",
    "output": null,
    "createdTime": "2022-05-30T23:56:24Z",
    "lastUpdatedTime": "2022-05-30T23:56:25Z"
}
```

During the incident, repeated logs(which is not from our code) show stalled schedule time
> c07d27ac11804a9e885998bda93d736e: Function job (Orchestrator) was resumed by a timer scheduled for 2022-05-30T23:57:25.9650000Z ...

From Log Analytics:
```
FunctionAppLogs
| where Message contains "c07d27ac11804a9e885998bda93d736e"
| where Message contains "was resumed by a timer scheduled for"
| extend scheduledTime = extract(" timer scheduled for (.*?) IsReplay", 1, Message)
| sort by TimeGenerated
| project TimeGenerated, scheduledTime, Message, FunctionName
```
![image](https://user-images.githubusercontent.com/28205157/171354791-fe5a102e-f44b-4a54-8a2f-fb1967f56fa3.png)

According to azure support, there were following exception
> I reviewed backend log and looks that orchestrator instanceId emitting below error since 05/31 00:10 UTC , my hypothesis is the previous termination causing something wrong in state storage so your orchestrator stuck for few hours. Not sure around 05/31 14:07:56 UTC what caused orchestrator run your activity function again which pull it out of loop.
> System.InvalidOperationException: Multiple ExecutionCompletedEvent found, potential corruption in state storage
>    at DurableTask.Core.OrchestrationRuntimeState.SetMarkerEvents(HistoryEvent historyEvent) in /_/src/DurableTask.Core/OrchestrationRuntimeState.cs:line 247
>    at DurableTask.Core.OrchestrationRuntimeState.AddEvent(HistoryEvent historyEvent, Boolean isNewEvent) in /_/src/DurableTask.Core/OrchestrationRuntimeState.cs:line 213
>    at DurableTask.Core.TaskOrchestrationDispatcher.ProcessWorkflowCompletedTaskDecision(OrchestrationCompleteOrchestratorAction completeOrchestratorAction, OrchestrationRuntimeState runtimeState, Boolean includeDetails, Boolean& continuedAsNew) in /_/src/DurableTask.Core/TaskOrchestrationDispatcher.cs:line 731
>    at DurableTask.Core.TaskOrchestrationDispatcher.OnProcessWorkItemAsync(TaskOrchestrationWorkItem workItem) in /_/src/DurableTask.Core/TaskOrchestrationDispatcher.cs:line 397
>    at DurableTask.Core.TaskOrchestrationDispatcher.OnProcessWorkItemSessionAsync(TaskOrchestrationWorkItem workItem) in /_/src/DurableTask.Core/TaskOrchestrationDispatcher.cs:line 192
>    at DurableTask.Core.WorkItemDispatcher`1.ProcessWorkItemAsync(WorkItemDispatcherContext context, Object workItemObj) in /_/src/DurableTask.Core/WorkItemDispatcher.cs:line 375
![image](https://user-images.githubusercontent.com/28205157/171353221-05cce768-bdc4-459a-b443-30d756cc713a.png)
![image](https://user-images.githubusercontent.com/28205157/171353273-ec9eb54c-1df0-457c-bd57-ccc5f4dcc6ce.png)

**Investigative information**

- Host.json
```
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[2.*, 3.0.0)"
  },
  "extensions": {
    "durableTask": {
        "storageProvider": {
            "connectionStringName": "AzureWebJobsStorage",
            "controlQueueBatchSize": 15,
            "controlQueueBufferThreshold": 30,
            "controlQueueVisibilityTimeout": "00:05:00",
            "maxQueuePollingInterval": "00:00:01",
            "partitionCount": 4,
            "workItemQueueVisibilityTimeout": "00:05:00"
        },
        "tracing": {
            "traceInputsAndOutputs": true,
            "traceReplayEvents": false
        },
        "maxConcurrentActivityFunctions": 15,
        "maxConcurrentOrchestratorFunctions": 15
    }
  }
}
```
- package.json
```
{
  "name": "monitor-az-func",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "prestart": "npm run build",
    "start": "func start",
    "test": "echo \"No tests yet...\""
  },
  "dependencies": {
    "@azure/arm-containerinstance": "^6.3.0",
    "@azure/loganalytics": "^0.2.0",
    "@azure/ms-rest-nodeauth": "^3.0.10",
    "@azure/storage-blob": "^12.7.0",
    "@azure/storage-queue": "^12.5.0",
    "bluebird": "^3.7.2",
    "durable-functions": "^1.5.0",
    "moment": "^2.29.1"
  },
  "devDependencies": {
    "@azure/functions": "^1.2.3",
    "@types/node": "^15.12.4",
    "typescript": "^4.0.0"
  }
}
```

***If deployed to Azure App Service***
- Timeframe issue observed: UTC 30 May 2022 23:57:00 ~ 31 May 2022 02:00:00
- Function App name: media-monitor-jobs-scheduler-durable-func-app
- Function name(s): job
- Region: uswest-2
- Orchestration instance ID(s): c07d27ac11804a9e885998bda93d736e

**To Reproduce**
Random issue.

> While not required, providing your orchestrator's source code in anonymized form is often very helpful when investigating ``
```
import * as df from "durable-functions"
import * as moment from 'moment';

const orchestrator = df.orchestrator(function* (context) {
    const params = context.df.getInput();

    if (params["start_time"] && params["end_time"]) {
        const startTimeEpochMS = Date.parse(params["start_time"]);
        const endTimeEpochMS = Date.parse(params["end_time"]);
        
        const currentTimeMS = context.df.currentUtcDateTime.getTime();
        if (currentTimeMS < startTimeEpochMS) {
            context.df.setCustomStatus("SCHEDULED");

            // Scheduling timer is limited
            // Ref: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-timers?tabs=javascript#timer-limitations
            const oneDayMS = 60 * 60 * 24 * 1000;
            const timeDiffMS = startTimeEpochMS - context.df.currentUtcDateTime.getTime();
            const waitUntilTime = timeDiffMS > oneDayMS ? new Date(context.df.currentUtcDateTime.getTime() + oneDayMS) : new Date(startTimeEpochMS);
            const abortTask = context.df.waitForExternalEvent("Abort");
            const sleepTask = context.df.createTimer(waitUntilTime);
            const winner = yield context.df.Task.any([abortTask, sleepTask]);
            if (!sleepTask.isCompleted) {
                // All pending timers must be complete or canceled before the function exits.
                sleepTask.cancel();
            }
            if (winner === abortTask) {
                context.df.setCustomStatus("STOPPED");
                return;
            }
            
            if (context.df.currentUtcDateTime.getTime() < startTimeEpochMS) {
                yield context.df.continueAsNew(params);
                return;
            }
        } else if (currentTimeMS >= endTimeEpochMS) {
            context.df.setCustomStatus("STOPPED");
            return;
        }
    }

    const hashCode = s => Math.abs(s.split('').reduce((a,b)=>{a=((a<<5)-a)+b.charCodeAt(0);return a&a},0));
    if (["ott_sync_check", "ott_basic_compliance"].includes(params["monitor_job_type"].toLowerCase())) {
        const jobStartTimeMS = context.df.currentUtcDateTime.getTime();
        
        try {
            context.df.setCustomStatus("RUNNING");
            yield context.df.callActivity('ott_check', params);
        } catch (err) {
            context.log.error(err);
        }

        const checkingIntervalMS: number = params["parameters"]["checking_interval_in_second"] * 1000;
        const ramdomizedBaseTimeMS = (hashCode(JSON.stringify(params)) % 3600) * 1000;
        const rebasedJobStartTimeMS = jobStartTimeMS - ramdomizedBaseTimeMS;
        const rebasedNextStartTimeMS = (Math.round(rebasedJobStartTimeMS / checkingIntervalMS) + 1) * checkingIntervalMS;
        const sleepTimeSecond: number = Math.floor((rebasedNextStartTimeMS - rebasedJobStartTimeMS) / 1000);
        const abortTask = context.df.waitForExternalEvent("Abort");
        const waitUntilTime = moment.utc(jobStartTimeMS).add(sleepTimeSecond, 's');
        const sleepTask = context.df.createTimer(waitUntilTime.toDate());

        const winner = yield context.df.Task.any([abortTask, sleepTask]);
        if (!sleepTask.isCompleted) {
            // All pending timers must be complete or canceled before the function exits.
            sleepTask.cancel();
        }
        if ( winner === abortTask ||
             (params["end_time"] && context.df.currentUtcDateTime.getTime() + checkingIntervalMS >= Date.parse(params["end_time"])) ) {
            context.df.setCustomStatus("STOPPED");
            return;
        }
    } else {
        let msg = `Unknown monitor_job_type: ${params["monitor_job_type"]}`;
        context.log.error(msg);
        throw new Error(msg);
    }

    yield context.df.continueAsNew(params);
});

export default orchestrator;
```
- static param for the job
```
{
    "task_id": "ac9206af-f2ae-4c17-b77a-566585ff9bef",
    "task_name": "[Apple HLS CBC] Game Feed 2 Slated Commercials",
    "start_time": "2022-04-14T01:46:48.798Z",
    "end_time": "2050-01-01T00:00:00.000Z",
    "monitor_job_type": "ott_sync_check",
    "parameters": {
        "ott_1": "https://origin-apple-east-prd-01.vos360.video/Content/HLS_CBC/Live/channel(g2nads)/master.m3u8",
        "ott_2": "https://origin-apple-west-prd-01.vos360.video/Content/HLS_CBC/Live/channel(g2nads)/master.m3u8",
        "azure_regions": [
            "westus2"
        ],
        "checking_interval_in_second": 60,
        "last_n_segments": 5,
        "ignore_period_id": false,
        "http_headers": [
            "x-cloudfront-header: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        ],
        "enable_g2o": false,
        "pager_duty_routing_key": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    }
}
```

**Expected behavior**
We expect the durable "job" is running every minute, and the activity "ott_check" is trigger at a regular 1 min interval.
eg: the log before incident:
![image](https://user-images.githubusercontent.com/28205157/171356518-d5dc0225-8471-4310-87dc-05dbf012fabc.png)

**Actual behavior**
Exception("System.InvalidOperationException: Multiple ExecutionCompletedEvent found, potential corruption in state storage") is observed, and the activity "ott_check" is not triggering

**Known workarounds**
Terminate the durable job, and start it again

**Additional context**
- Development environment (ex. Visual Studio): vscode

**Comment by lilyjma** [comment]
@chanyk-joseph - Are you still experiencing the issue? If yes, could you try upgrading to the new SDK and reproduce the issue?
