### ISSUE TITLE
Error: Choose either to return a promise or call 'done'. Do not use both in your script.

### ISSUE THREAD

**Issue by sladkoff** [Azure/azure-functions-durable-js#373]
**Describe the bug**
The following error log is shown in the local console when running and executing durable entity functions:

```
Error: Choose either to return a promise or call 'done'. Do not use both in your script. Learn more: https://go.microsoft.com/fwlink/?linkid=2097909
```

**Investigative information**

```
Azure Functions Core Tools
Core Tools Version:       4.0.4590 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.5.2.18383
```

```
node -v
v16.15.0
npm -v
8.12.2
```

**To Reproduce**

function.json:
```json
{
  "bindings": [
    {
      "name": "context",
      "type": "entityTrigger",
      "direction": "in"
    }
  ],
  "scriptFile": "../dist/entity-name/entity.js"
}
```

function.ts:
```ts
export default entity<EntityType>(context => {
   // handleOperation(context)
});
```

**Expected behavior**
No error should be logged.

**Actual behavior**
An error is logged.

**Screenshots**
![image](https://user-images.githubusercontent.com/6025787/176718035-21ff5f44-2e28-4471-a7e7-0ee5ffb6c457.png)

**Additional context**

This seems to be related to how the `entity()` function and `Entity` class are implemented internally (?).

- [Here](https://github.com/Azure/azure-functions-durable-js/blob/dev/src/shim.ts#L35-L37) a promise is returned.
- [Here](https://github.com/Azure/azure-functions-durable-js/blob/dev/src/entity.ts#L70) `context.done(...)` is called.

**Comment by ejizba** [comment]
As a bit of background - I fixed a bug in https://github.com/Azure/azure-functions-nodejs-worker/pull/555 where this log was not getting displayed to users even though it has been around for a long time. The fix recently rolled out which is why you're seeing this error now.

Using both async/await & context.done can lead to very unpredictable behavior, in other words this specific case could be very problematic or it could have no effect on the user at all. Suffice to say it's worth investigating

**Comment by davidmrdavid** [comment]
Thanks for the report @sladkoff.

Any chance you could provide us with a minimal repro of this behavior? That would help accelerate this investigation. Thanks!
FYI - @hossam-nasr

**Comment by epomatti** [comment]
@davidmrdavid here's how to reproduce the issue.

1 - Create the function app components:

```sh
func init --worker-runtime "node" --language "javascript"

func new -n "counter" -t "Durable Functions entity"
func new -n "counter-client" -t "Durable Functions Entity HTTP starter"
```

2 - Add the `durable-functions` dependency:

```sh
npm i durable-functions
```

3 - Start Azurite:

```sh
azurite -s -l /tmp/azurite
```

4 - Edit the `local.settings.json`. Need to modify it with the Account Key from Azurite (or a real Storage if you prefer to use it):

```json
{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "node",
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "AzureWebJobsDashboard": "UseDevelopmentStorage=true",
    "QueueConnectionString": "AccountName=devstoreaccount1;AccountKey=<<<ACCOUNT_KEY>>>;DefaultEndpointsProtocol=http;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;"
  }
}
```

5 - Start it and call the function:

```sh
func start

# Run this to trigger the error
curl -X POST http://localhost:7071/api/counters/myCounter

# This runs fine
curl http://localhost:7071/api/counters/myCounter
```

My environment:

```sh
$ func --version
4.0.4785

$ node --version
v16.17.1

$ azurite --version
3.19.0

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

**Comment by davidmrdavid** [comment]
Thanks @epomatti , I'm aware of this issue and want to fix it asap.
@ejizba: I recall you said we should be able to bypass this error by updating our types package for azure-functions. Can you please clarify exactly what version we need to upgrade to, and whether there's any code changes needed in addition to the types upgrade?

**Comment by hossam-nasr** [comment]
Hi @davidmrdavid , there's still changes that would be required on the Azure Functions framework, to enable us to safely call `context.done()` without this warning being logged. That work is being tracked here: https://github.com/Azure/azure-functions-nodejs-library/issues/22. After this work is done, we would need to update the Durable SDK to set that new flag when calling `context.done()` in our Entity implementation

**Comment by davidmrdavid** [comment]
Thanks @hossam-nasr. When's the earliest we can fix this in the library? This warning is quite confusing and discouraging to users.

**Comment by hossam-nasr** [comment]
@davidmrdavid The change needed at first glance seems to be pretty simple, so it just depends on how we want to prioritize this compared to other high pri items 😛 I should also be careful here, because we need to make sure we make this change in a backwards compatible way, so the change may not actually be as simple as it appears
