### ISSUE TITLE
DummyOrchestrationContext does not initialize df

### ISSUE THREAD

**Issue by eva-ortuno** [Azure/azure-functions-durable-js#378]
During tests, `DummyOrchestrationContext` allows to mock the context of a durable function. The property `df` of the  dummy context is not initialised anymore with version 2. This prevents mocking `callEntity`, `callActivity`, ...  and the execution of orchestrator functions. 
Is there a reason to remove the init. from the dummy orchestrator ? 

To reproduce the error, I used the samples provided in the repository : [samples - UnitTesting](https://github.com/Azure/azure-functions-durable-js/tree/2.0.2/samples/UnitTesting). After updating the version of `durable-functions` for this example, the test fails with the error : 
![image](https://user-images.githubusercontent.com/90448715/185437607-71f44f00-3714-40a0-b9bf-44ad45e56aa0.png)
at the position : 
![image](https://user-images.githubusercontent.com/90448715/185437703-570c8eb4-76e0-4384-b603-45da561d456e.png)

**Comment by davidmrdavid** [comment]
Thanks @eva-ortuno, this is a good catch. This ought to be something we should be able to fix. Let me take a look at this as soon as possible.

FYI - @hossam-nasr.

**Comment by waqasraz** [comment]
Any update or work around?

**Comment by davidmrdavid** [comment]
No updates yet, unfortunately.
@hossam-nasr - we should look to prioritize this. I can help make this change as well

**Comment by hossam-nasr** [comment]
Hi @eva-ortuno and @waqasraz, I apologize for the delay responding to this issue.

I did some investigation, and it looks like this is not going to be a simple bugfix as I initially thought. When moving to v2.x, we restructured the way the SDK executes orchestrations and interprets the History array, and it looks like unfortunately we broke the unit-testing story we had in v1. We would have to design a new unit-testing experience, something we already have an issue for v3.x: #420. As this may require a major effort, this is not something we would pursue for v2.x at this time. 

I will close this issue in favor of #420, but rest assured that unit-testing is one of our priorities and focus areas for v3.x. We welcome any suggestions you may have for how you want unit tests to look like in v3! Please leave your thoughts and comments on #420. Thanks!
