### ISSUE TITLE
Support the new Node.js programming model in durable

### ISSUE THREAD

**Issue by ejizba** [Azure/azure-functions-durable-js#384]
More info here: https://aka.ms/AzFuncNodeV4

Here are my recommended steps to do this in an incremental fashion:
1. This will be a breaking change, there's no way around that. So to start, I'd create a new branch, maybe "v3.x" and update the version of this package to "3.0.0-alpha.1"
2. I would update the reference of "@azure/functions" in the `package.json` to "4.0.0-alpha.2"
3. I would fix all the build errors (there will be a lot lol) and submit a PR
4. Now, I would try to get it to actually run locally 😅 That means following steps [here](https://aka.ms/AzFuncNodeV4) and using `app.generic` to register durable functions. Once it works locally, I'd submit another PR as I doubt the changes from step 3 will work on the first attempt
5. Finally, I would add fancy intellisense for `app.durable` methods. Currently tracked by [this issue](https://github.com/Azure/azure-functions-nodejs-library/issues/8), but open for discussion where that code lands. Regardless, ideally this is a separate PR

**Comment by hossam-nasr** [comment]
First alpha v3 release of the SDK with programming model support is out now! 🎉

For further work on the programming model, discussions and improvements, closing this in favor of #393, #394, #414, #415, #416, #417, #418, #419, #420, #421
