### ISSUE TITLE
Orchestration Instance still "Running" when stopped after error is thrown

### ISSUE THREAD

**Issue by mitchellkeys** [Azure/azure-functions-durable-js#390]
**Describe the bug**
When an error is manually thrown within the Orchestrator, it successfully stops the instance, but the state is left at "Running" rather than "Failed". 

**Mock Example Code**
``` typescript
const callActivityWithRetry = function* (
    context: IOrchestrationFunctionContext,
    activity: string
) {
    context.log(`Calling ${activity}...`);
    object = (yield context.df.callActivityWithRetry(
        activity,
        new df.RetryOptions(100, 2)// Dummy Numbers
    )) as KnownType;

    throw "Error would be thrown here!"

    context.df.setCustomStatus(object);
    return object;
};

const orchestrator = df.orchestrator(function* (context: IOrchestrationFunctionContext) {

    someObject= yield* callActivityWithRetry (context, "ActivityName");

    return someObject;
});
```

**Investigative information**

- Durable Functions extension version: ~4 (Not too sure on this one)
- durable-functions npm module version: 2.0.2
- Language (JavaScript/TypeScript) and version: TypeScript/4.7.4
- Node.js version: 14 LTS

***If deployed to Azure App Service***

- Timeframe issue observed: ~Nightly
- Function App name: backout-function-app
- Region: West US 3

_^ Teams @mitchellkeys for more info!_

**To Reproduce**
1. Start a DF Orchestration,
2. Manually throw an error,
3. Check the instances azure table to see if status is "Running"

**Expected behavior**
When an error is thrown within the DF Orchestration, I'd expect it to report a "Failed" status.

**Actual behavior**
When an error is thrown within the DF Orchestration, it reports a "Running" status.

- Development environment: VS Code

**Comment by davidmrdavid** [comment]
Hi @mitchellkeys,

Thanks for reaching out. Do you have a local, minimal, repro of this that you could attach to this thread? That would help us get to the bottom of this. Thanks!

**Comment by mitchellkeys** [comment]
For sure:

I'm using nested Generator functions to help create some polling methods, here is an example orchestrator method:

``` typescript
 const callActivityWithRetry = function* (
    context: IOrchestrationFunctionContext,
    activity: string,
    count: number
) {
    context.log(`Calling ${activity}...`);
    count = (yield context.df.callActivityWithRetry(
        activity,
        new df.RetryOptions(
            1000,
            3
        ),
        count
    )) as number;
    context.df.setCustomStatus(count);
    throw "Error here!"
    return count;
};

const orchestrator = df.orchestrator(function* (context) {
    let count = 0;

    count = yield* callActivityWithRetry(context, "PollingActivity", count);

    return count;
});

export default orchestrator;

```

The Activity function will run just fine, but once I throw the error within the generator context, it will stop the instance, but the instance status will still be set at "running".

**Comment by davidmrdavid** [comment]
Responded internally. However, the key issue here is that the SDK exceptions exceptions to be of type `Error` (or a subclass).

Therefore, if you change `throw "error here!"` to `throw new Error("error here!")` then it should work correctly :).

I'd say this is a bug on our end, we should be able to handle arbitrary exceptions. I'm making a note to fix this.

**Comment by mitchellkeys** [comment]
Awesome thanks, this solved the issue I was seeing.

Issue is being tracked [here](https://github.com/Azure/azure-functions-durable-js/issues/391), and I am no longer blocked, so I'm closing this issue.
