### ISSUE TITLE
Azure Functions types are outdated

### ISSUE THREAD

**Issue by hossam-nasr** [Azure/azure-functions-durable-js#400]
Currently, v2 of this SDK lists `@azure/functions` types package version `1.2.3` in its dependencies, which is very outdated. For reference, the latest stable release of `@azure/functions` is `3.2.0`. This means that the types the users get do not reflect the code actually being run (in the vast majority of cases). This issue is to collect feedback and discuss the best approach to fix this problem.

I can think of a few options:

### 1. Upgrade to the latest version, keeping it in the dependencies:

This seems like the most straightforward answer, but it has a few downsides. For one, users who somehow depended on the old types might now find themselves unable to compile their code. This may not be a huge concern for us though, because that would indicate their app was already broken in a more fundamental way. The only exception would be customers running on v2 of the Functions runtime, for whom v1 of `@azure/functions` _is_ the right version to use.

Secondly, this option will also mean that this error in the `@azure/functions` library: https://github.com/Azure/azure-functions-nodejs-worker/issues/587 will propagate down to the SDK as well, meaning that Durable TypeScript apps that do not explicitly list `@types/node` in their dependencies will now fail to compile. If we go this option, it would be up to us to decide if this change should be treated as a breaking change and left to a next major version release, or if it's okay to settle for only a minor version upgrade.

Lastly, this fix is also not ideal because it doesn't _really_ fix the underlying issue. Depending on which function runtime version the customer is using, the actual implementation may not match the latest version of the types in `@azure/functions`. Because we support multiple different versions of the Functions Runtime in our code, there really isn't a perfect way to do this while keeping `@azure/functions` as a dependency in our own SDK. The best we can do is pick the version of the types package that matches _most_ users, or to pick the lowest version for the lowest version of Functions that we support, or some other heuristic. 

### 2. Upgrade to the latest version, but move it to devDependenies:

This might be the most "correct" solution, but also the most "breaking." Stricly speaking, we only use `@azure/functions` for types (at least for now), and since it's not used in production, then it "should" be in our devDependenies. Doing so will allow us to use the latest types in our own code, while shifting the burden to the user to install the right version of `@azure/functions` that matches their runtime version. However, this would mean that any Durable TS project that doesn't specify `@azure/functions` _and_ `@types/node` in their dependencies (or devDependencies) would now fail to build, an extra burden on the customer that wasn't there before.

### 3. Leave this as-is and only upgrade the version in v3 of this package (new programming model):

Starting from v3 of this package, we would have to specify v4 `@azure/functions` as a hard dependency anyway, because it will include the actual source code implementation of the programming model, not just the types.

Given all the above, I would suggest moving with option 2, and I wouldn't consider it a breaking change. At the end of the day, it doesn't cost much to the customer to install the right version of `@azure/functions` and `@types/node` for their app, and they _should_ be doing that anyway. If they really don't want to be doing that, they could pin to a specific minor version of our SDK. If we go this option, we would have to be clear in our release notes that TS users now have to specify `@azure/functions` and `@types/node` in their devDependencies. We should also update our guides, readmes, and samples accordingly.

**Comment by hossam-nasr** [comment]
cc @ejizba @davidmrdavid

**Comment by davidmrdavid** [comment]
@hossam-nasr: 

I want to explore option (3) a little bit.

For (3), you said that we will need to specify v4 as a hard dependency. Does that mean that it will not be a dev-dependency but a proper "full" dependency instead? Just checking!

Does that mean that, if version v5 of @azure/functions came out, we would need to make yet another breaking change release of the SDK?

**Comment by davidmrdavid** [comment]
Alternatively, I think it would be wise for us to reconsider the way in which we're exposing types from @azure/functions. It's not fully clear to me that we actually need to export augmented versions of those types.

**Comment by ejizba** [comment]
I'm leaning towards option 3. AFAIK, we have not received any feedback from users complaining about the outdated types. The v1 types and v3 types are not _that_ much different. I just think we have other areas that are higher priority, so why rock the boat when no one has asked us to. It also feels like the work for option 1 or 2 is throwaway work because things will be different in the new model anyways.

**Comment by davidmrdavid** [comment]
I also do lean towards option (3) for what it's worth. I'd rather not break V2 customers, especially if there's no community feedback about the types being off.

**Comment by michaeldisaro** [comment]
Hi guys, v3 types are fully supporting the runtime V4 of Azure Functions. Azure functions V3 runtime will be "terminated" December 3rd 2022. 

Are we sure that v1 vs v3 types small differences are not going to break anything?

**Comment by arcogabbo** [comment]
Looking forward to this.

**Comment by davidmrdavid** [comment]
@michaeldisaro, my understanding is that our dependency on an outdated types package has a very limited impact area.
This is because they were included for the purpose of developing the SDK itself. In that sense, their inclusion as a proper dependency instead of a dev-dependency is the "real" problem. Yes, we export a handful of types that subclass other types from @azure/functions, but I understand that mostly corresponds to the orchestrationContext whose usage is already highly constrained :-) .

In that sense, the DF NodeJS SDK today works as expected in Functions V2, V3, and V4 even with its outdated types dependency. Of course, there are probably a few edge cases where an inherited property may be outdated, and those should be fixed (or ideally those unwanted inherited properties would be removed altogether), which is why we have this tracking issue.

**Comment by hossam-nasr** [comment]
Based on the discussion here, looks like we're going with option 3, leaving the `@azure/functions` version as it is in the v2 version of `durable-functions`, but updating it in `v3` for the new programming model (already done). Closing this issue
