### ISSUE TITLE
Orchestrator values are not passed if not objects

### ISSUE THREAD

**Issue by Nepomuceno** [Azure/azure-functions-durable-js#42]
If I have a simple string the orchestrator return no input values
```js
client.startNew(orchestrator, undefined, "bla")
```
```js
const input = context.df.getInput();
// input will be null;
```

I imagine this can be related with the change to use Axios now.
And in order to make my code work I needed to change the code in start new from
```js
const response = await axios.post(requestUrl, JSON.stringify(input));
```
to
```js
const response = await axios.post(requestUrl, input);
```

**Comment by sckelly** [comment]
I'm getting this too when I pass a JSON object to the HttpTrigger and then Orchestrator :cry: 
Debugging the getInput() function right now to check for a work-around

**Comment by kashimiz** [comment]
Oh dear. I'll hop right on this one; thank you for bringing it to my attention, @Nepomuceno!
