### ISSUE TITLE
Should we continue to support compound tasks with no children?

### ISSUE THREAD

**Issue by hossam-nasr** [Azure/azure-functions-durable-js#424]
Currently, the SDK supports creating compoung `Task`s (e.g.., `WhenAny`/`WhenAll` tasks) without any children. This support can lead to weird scenarios such as #423. Perhaps we should consider not supporting this scenario anymore in v3 (See discussion: https://github.com/Azure/azure-functions-durable-js/issues/423#issuecomment-1397694184)

**Comment by davidmrdavid** [comment]
@hossam-nasr: Did we both end up creating the same issue: - https://github.com/Azure/azure-functions-durable-js/issues/423#issuecomment-1397701924

**Comment by davidmrdavid** [comment]
oh I see, this is for v3 support only. Nevermind.

**Comment by hossam-nasr** [comment]
Discussed offline. Let's not support this scenario in v3 and throw an error when we find it

**Comment by hossam-nasr** [comment]
Closed by #463
