### ISSUE TITLE
`log` and friends missing on IFunctionContext

### ISSUE THREAD

**Issue by poelstra** [Azure/azure-functions-durable-js#46]
`IFunctionContext` as defined in `durable-functions` doesn't have the `log` property (and others).

![image](https://user-images.githubusercontent.com/1025628/52398672-26845080-2aba-11e9-9e99-1bcc46237cb5.png)

It would be nice if it could use a more 'in-sync' definition such as from [`@azure/functions`](https://github.com/Azure/azure-functions-nodejs-worker/tree/master/types/public)

**Comment by kashimiz** [comment]
Hi @poelstra,

When `durable-functions` moved to GA availability the TypeScript definitions weren't yet available, but now that they are, you're absolutely right that we should be using them. Putting this on the list of enhancements for our next release.

**Comment by bernitorres** [comment]
Is there a workaround to log messages in the orchestrator function in typescript?

**Comment by kashimiz** [comment]
@bernitorres, the `context` object still has the log method; it's just not defined in the TypeScript interface. Have you tried something like the following?

`(context as any).log("This is my log message.");`

**Comment by bernitorres** [comment]
I should have known that.. thanks! That unblocked me

**Comment by kevinclarkneudesic** [comment]
I found this same issue.  Why was durable-functions or @azure/functions not written in TypeScript??  Seems amazing that a modern library esp. by Microsoft would be written in vanilla JS.  Then there would not be a need for manually creating definition files. (facepalm)

**Comment by poelstra** [comment]
> Why was durable-functions or @azure/functions not written in TypeScript

They are. See https://github.com/Azure/azure-functions-durable-js/issues/46#issuecomment-461548061 though.

**Comment by kevinclarkneudesic** [comment]
> > Why was durable-functions or @azure/functions not written in TypeScript
> 
> They are. See [#46 (comment)](https://github.com/Azure/azure-functions-durable-js/issues/46#issuecomment-461548061) though.

Sorry, haven't had my coffee yet. :/  Lol.  I re-read and think I understand the issue now, since they are two separate libraries they were out of sync?

**Comment by poelstra** [comment]
Something like that, yes.
