### ISSUE TITLE
Ensure autogenerated docs continue working for v3

### ISSUE THREAD

**Issue by hossam-nasr** [Azure/azure-functions-durable-js#475]
Followup to #473:

> Ensure that our autogenerated docs [here](https://learn.microsoft.com/en-us/javascript/api/durable-functions/?view=azure-node-latest) continue working after all these changes. Definitely not a preview blocker, but I'd like to finish this validation before GA.

_Originally posted by @davidmrdavid in https://github.com/Azure/azure-functions-durable-js/pull/473#pullrequestreview-1291619107_

**Comment by ejizba** [comment]
Fixed in:
https://github.com/MicrosoftDocs/azure-docs-sdk-node/pull/1551
https://github.com/Azure/azure-sdk/pull/6709
