### ISSUE TITLE
OrchestratorClient fails when waiting for completion

### ISSUE THREAD

**Issue by nickyhof** [Azure/azure-functions-durable-js#55]
This does not happen all the time but occasionally the orchestration client fails when waiting for completion.

**Error**
```
Orchestrator function 'createOrchestrator' failed: TypeError: Cannot read property 'Timestamp' of undefined
    at Orchestrator.<anonymous> (D:\home\site\wwwroot\node_modules\durable-functions\lib\src\orchestrator.js:88:74)
    at Generator.next (<anonymous>)
    at D:\home\site\wwwroot\node_modules\durable-functions\lib\src\orchestrator.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (D:\home\site\wwwroot\node_modules\durable-functions\lib\src\orchestrator.js:3:12)
    at Orchestrator.handle (D:\home\site\wwwroot\node_modules\durable-functions\lib\src\orchestrator.js:22:16)
    at D:\home\site\wwwroot\node_modules\durable-functions\lib\src\shim.js:8:9
    at WorkerChannel.invocationRequest (D:\Program Files (x86)\SiteExtensions\Functions\2.0.12342\32bit\workers\node\worker-bundle.js:16077:26)
    at ClientDuplexStream.WorkerChannel.eventStream.on (D:\Program Files (x86)\SiteExtensions\Functions\2.0.12342\32bit\workers\node\worker-bundle.js:15967:30)
    at ClientDuplexStream.emit (events.js:182:13)
```

This issue seems to happen here: https://github.com/Azure/azure-functions-durable-js/blob/b1512bf7b365b4ff72046934cc9c008c042aff08/src/orchestrator.ts#L105

I resolved this by adding a check on decisionStartedEvent. Similar to whats being done here: https://github.com/Azure/azure-functions-durable-js/blob/b1512bf7b365b4ff72046934cc9c008c042aff08/src/orchestrator.ts#L55-L57

**Comment by nickyhof** [comment]
Created a PR here: https://github.com/Azure/azure-functions-durable-js/pull/56

**Comment by kashimiz** [comment]
Hi @nickyhof, thanks for reporting this issue, and for your PR! I'm going to merge it in; however, I'm curious about the conditions under which `decisionStartedEvent` is `undefined`, because it should always have a value. Do you have a scenario that consistently produces the behavior you reported? That would be a big help to determine and fix the underlying cause.

**Comment by nickyhof** [comment]
Hi @kashimiz, unfortunately no. I tried figuring out what was causing the issue when submitting this ticket to give you more context but it almost seems to happen randomly. If anything comes up I'll definitely let you know. Thanks for looking at the PR!

**Comment by amclin** [comment]
I am seeing this now in my functions. It happens fairly consistenty and every entry in the DurableFunctionsHubInstances table is listed as `failed` with the same stack trace as reported here. I'm not clear when it started, so I'm trying to step back through my project's changes to see where it was introduced. I'm using the "chained function" pattern.

**Comment by kashimiz** [comment]
Hi @amclin, thank you for this data; it helps a lot. Because `durable-functions` implements orchestrators using generators, a `yield` statement within an orchestrator is processed as one of the async actions called through the durable orchestration context (ex. callActivity, createTimer, waitForExternalEvent, etc.) 

A user-defined synchronous function like `logCompletedState` can and should be called without `yield.`

That said, a more helpful error message wouldn't be amiss here. Flagging as an enhancement for our next release.

**Comment by amclin** [comment]
@kashimiz I've noticed quite a few issue reports on this project that ultimately can be traced to hijacking the generator/yield syntax to simulate the C# async behavior that Durable Functions depend on. I think it's causing a high level of confusion and could benefit from some thorough documentation explaining how it differs from normal JS behavior, limitations, etc.

**Comment by kashimiz** [comment]
Thank you for this feedback, @amclin, and my apologies for taking so long to respond.

We do include mention of how to use the `yield` syntax throughout the documentation, such as [here](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-checkpointing-and-replay#orchestrator-code-constraints) and [here](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-concepts#event-sourcing-checkpointing-and-replay), but I wouldn't call it thorough, nor does it mention generator syntax. We could definitely call this out in a more obvious fashion.

I've filed a [new issue](https://github.com/Azure/azure-functions-durable-js/issues/79) to track this.

**Comment by anthonychu** [comment]
Closing as it looks like this is now a docs issue tracked here: https://github.com/Azure/azure-functions-durable-js/issues/79.
