### ISSUE TITLE
API Implementation Timeline

### ISSUE THREAD

**Issue by deman4ik** [Azure/azure-functions-durable-js#6]
Have you any timeline on releasing "Not Yet Implemented" APIs from Checklist?
I know that durable functions are only in preview now, but we need to know will we be able to completely switch from c# to js in the near future?

**Comment by amileoj** [comment]
We would like to know this as well. We will soon be starting a major new initiative using durable functions and we need to come to a determination pretty quickly as to whether to use C# or Node.js. The latter fits much better with our existing tech stack but if GA is not going to happen relatively soon then we may be forced to go the former route, or find a different orchestration method altogether.

**Comment by deman4ik** [comment]
I received a response from @cgillum in [azure-functions-durable-extension repository](https://github.com/Azure/azure-functions-durable-extension/issues/380#issuecomment-403083808).

> The plan is to have the JS features GA by this fall, alongside the GA of Functions v2. As part of that GA, all the features in the checklist are expected to be implemented.
