### ISSUE TITLE
Singleton orchestrator with re-run-once-at-end

### ISSUE THREAD

**Issue by eirikb** [Azure/azure-functions-durable-js#60]
Hi

This is a question, not an issue (could be tagged question).
Is it possible to have a singleton orchestrator which would re-run at end?

Our setup works like this:

- Singleton orchestrator
- Triggered by SharePoint upon item change (update/create)
- Loads items "changed last 30 minutes"
- Works on these items in actions
- Every time the trigger is re-called while the orchestrator is running it will wait until it's complete, then run it again for every trigger

That last step should look more like this:

- Every time the trigger is re-called while orchestrator is running it should flag that a change has happened, and the orchestrator should re-run _once_ when complete

What we want to get rid of is the amount of times the orchestrator is run, for example if our function is triggered 5 times while the orchestrator is running all of these triggers will cause a full run at the end, while we actually only need one single run at the end.
The first trigger should cause a run, and if triggered while running it should run once more to handle the items changed while running.

This could perhaps be solved using a simple queue or blob, with a flag that can be checked at the end, but is it atomic enough?

Here is our HTTP endpoint creating the singleton orchestrator.
I've read that a hard coded `instanceId` should create a singleton, but this code is the only way which has worked for me:

```JavaScript
const df = require("durable-functions");

module.exports = async function (context, req) {
  const client = df.getClient(context);
  const instanceId = 'subscription';

  const status = await client.getStatus(instanceId);
  if (status && status.runtimeStatus === 'Running') {
    const timeoutFourMinutes = 4 * 60 * 1000;
    const intervalTenSeconds = 10 * 1000;
    await client.waitForCompletionOrCreateCheckStatusResponse(
      req, instanceId, timeoutFourMinutes, intervalTenSeconds);

    // Just to be sure, might be superfluous
    await client.terminate(instanceId, 'Timeout');
  }
  await client.startNew('SubscriptionOrchestrator', instanceId, req.query);
  return client.createCheckStatusResponse(context.bindingData.req, instanceId);
};
```

**Comment by kashimiz** [comment]
There may be a more straightforward solution here, but I need more information to be sure. Could you elaborate on what your system is intended to do? My impression is that you want to continuously process changed items from SharePoint in parallel, but I'd like to verify.

**Comment by eirikb** [comment]
Yes it processes changed items from SharePoint in parallel, but I don't want the same action to run simultaneously against an item, this can lead to save conflicts.  
Orchestrator will initially load all changed items, and then run different actions. If a user changes an item while the job is running I don't want to immediately start another job but instead start a new one when the current job has finished.

**Comment by kashimiz** [comment]
Would the following setup accomplish your goal?

- Use a timer-triggered starter function to check whether your eternal orchestration is currently running; if not, start it with an input of a timestamp equal to `current time - <X minutes>`.
- In your eternal orchestration, retrieve the input.
- Call an activity that retrieves changed items from X minutes ago based on the input. (Making some assumptions about SharePoint's APIs here, but if they require a time interval versus a timestamp, that could be calculated from the orchestrator's `context.CurrentUtcDateTime` and its input timestamp.)
- Process the changed items.
- Call `context.continueAsNew(context.CurrentUtcDateTime)`.

**Comment by eirikb** [comment]
Would this make the Orchestrator run forever?
I'm currently starting the orchestrator from a webhook, SharePoint send a ping when something has changed, so it can have a lot of idle time.  
What if I write to a blob from my webhook, and in an eternal orchestrator check if the blob has changed?

**Comment by kashimiz** [comment]
Yes, the orchestrator would run continuously. I was under the impression you needed to handle a constant stream of changes in parallel, rather than intermittently as you clarified.

I think that could work, but can you elaborate? Would you have an eternal orchestrator that polls the blob for changes and retrieves/processes them if any are detected?

You could also change the orchestrator I described above to use a webhook trigger, using the continueAsNew mechanism, and end if it retrieves no more changes. This setup wouldn't have to run continuously.

**Comment by eirikb** [comment]
> I think the blob approach could work, but can you elaborate? Would you have an eternal orchestrator that polls the blob for changes and retrieves/processes them if any are detected?

Yes the idea was to have a blob to flag that changes have been made. Not sure if the orchestrator should check this or a timer trigger.
> You could also change the orchestrator I described above to use a webhook trigger, using the continueAsNew mechanism, and end if it retrieves no more changes. This setup wouldn't have to run continuously.

That sounds like a good idea. In order to known if changes have occurred would I then also need a blob? Perhaps something like this:

1. Webhook is called (SharePoint item has changed)
1. `if` orchestrator is not running then start it
1. `else` write to a blob that a change has occurred
1. At end of orchestrator it checks if blob has data  
   and if it does then call `continueAsNew`

**Comment by kashimiz** [comment]
I don't think you would need the blob if you had something like this:

**Webhook**
1. triggers when a SharePoint item has changed
2. `if` orchestrator is not running then start it
3. `else` do nothing

**Orchestrator**
1. Calls `context.GetInput`, which is the last checkpoint time. If input is `null`, use `context.CurrentUtcDateTime - <some default interval, ex. 30 minutes>`.
2. New checkpoint time = `context.CurrentUtcDateTime` // necessary to preserve it here because it updates per replay
3. (In an activity) Load items changed since the last checkpoint time.
4. `if` 0 items retrieved, `return` to end the orchestration.
5. (In parallel activities) Process changed items.
6. Call `continueAsNew`, passing in new checkpoint time.

If it's readily available, you could also use the timestamp of the most recently updated item you retrieved in step 3 as a checkpoint time.

**Comment by eirikb** [comment]
I see, that's really clever, the trigger only starts the orchestrator, it's the item count that matters.
Since getting the items is the first thing I do I can quit the orchestrator there (as I already do), and then the last step could be to always run `continueAsNew`.
Thanks.
Oh and, I must check the the orchestrator is running in my webhook? Simply having a hard coded `instanceId` is not enough?

**Comment by kashimiz** [comment]
Yes; `startNew` overwrites any existing orchestrator with that `instanceId`, so your webhook function should check that the orchestrator isn't currently running before you calling that method.

**Comment by eirikb** [comment]
I've implemented this now, and it's looking really good. Thanks a bunch!

**Comment by eirikb** [comment]
Hi again

I'm so sorry to bring this back up, but I've experienced some problems. I'm fairly sure I had it working, but now I had to revert my changes, as it seems the orchestrator is never re-run.

I've created a small example project based on my original code.  
Main difference is that action to get SharePoint items is a dummy, and Hello action is a dummy. Starter and Orchestrators are identical to what I had in production.

---
### https://github.com/eirikb/durable-demo
Flow works like this:
  1. Item in SharePoint is updated, Start is called.
  1. Start will start new Orchestrator if not already running. Terminate + start if it has been running for too long.
  1. Orchestrator calls GetItems (without stamp) to get items changed last couple of minutes.
    1. If items then run actions, or else quit.
    1. Call `continueAsNew` inlcuding a stamp
    1 Should continue at 2, but with a stamp <-- This never happens

**Comment by eirikb** [comment]
Update; Passing in `null` to `callSubOrchestrator` would actually cause the Orchestrator to never be flagged as Compelted, using the trick from other issues: 
```JavaScript
return yield context.df.callSubOrchestrator('Orchestrator', {stamp, ...input}, `${context.df.instanceId}:0`);
```

**Comment by eirikb** [comment]
Another update, the `callSubOrchestrator` didn't work very well, today it ended up in an endless loop. I'm not sure why, it's hard to tell from the logs.  
Suddenly I had > 10k log messages in application insights, and if not for some safe-checks it would have sent out some thousand e-mails.
