### ISSUE TITLE
Method to check if orchestration exists

### ISSUE THREAD

**Issue by gpa** [Azure/azure-functions-durable-js#610]
I want to check if a given ID exists. Currently I have to do:
```typescript
    try {
        const status = await client.getStatus(internalRequestId);
      } catch(err) {
        if (err instanceof Error && err.message.includes('replied with HTTP 404 response. This usually means we could not find any data associated with the instanceId provided')) {
          console.log(err);
        } else {
          throw err;
        }
      }
```
Seems like this could be improved. Or is there a better way to check this?
In V3 undefined was returned.

**Comment by gpa** [comment]
This method is also throwing an `Error` while a `DurableError` would be expected.

**Comment by davidmrdavid** [comment]
Thanks @gpa - I think the implementation is fine, though I agree it looks a bit involved. Seems to me that the `DurableError` type could provide a better API here to simplify the sample.

But as you noted in your other issue, we should first make sure the `DurableError` type is properly exposed, let's us try to tackle that first.
