### ISSUE TITLE
Azure function apps authentication bug

### ISSUE THREAD

**Issue by KieranDaviesV** [Azure/azure-functions-durable-js#62]
**Describe the bug**
When durable function is up in Function apps, using the function apps authentication, i receive a 500 error status. along with:

  Exception: Error: You do not have permission to view this directory or page.
Stack: Error: You do not have permission to view this directory or page.
    at DurableOrchestrationClient.<anonymous> (D:\home\site\wwwroot\node_modules\durable-functions\lib\src\durableorchestrationclient.js:247:43)
    at Generator.next (<anonymous>)
    at fulfilled (D:\home\site\wwwroot\node_modules\durable-functions\lib\src\durableorchestrationclient.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Investigative information**

- Durable Functions extension version: 1.7.1
- Function App version (1.0 or 2.0): 2.0
- Programming language used: Javascript

***If JavaScript***

- durable-functions npm module version: 1.1.4

***If deployed to Azure***

- Timeframe issue observed:  2:51:24 pm gmt
- Function App name: sitecreatorv2
- Function name(s): httpRequest
- Region: North Europe
- Orchestration instance ID(s): -- didn't get that far

> If you don't want to share your Function App name or Functions names on GitHub, please be sure to provide your Invocation ID, Timestamp, and Region - we can use this to look up your Function App/Function. Provide an invocation id per Function. See the [Functions Host wiki](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately) for more details.

**To Reproduce**

1. fire http request
2. view logs to see error

> While not required, providing your orchestrator's source code in anonymized form is often very helpful when investigating unexpected orchestrator behavior.

**Expected behavior**
Should fire off my orchestrators

**Actual behavior**
Errors out with You do not have permission to view this directory or page.

**Screenshots**

**Known workarounds**
Provide a description of any known workarounds you used.

**Additional context**

- Development environment (ex. Visual Studio)
- Links to source
- Additional bindings used
- Function invocation IDs

**Comment by cgillum** [comment]
Unfortunately this is a limitation of the JavaScript orchestration client. It schedules orchestrations by making an HTTP call to the current function app, but if access to that function app is protected by Authentication / Authorization, then these client calls will fail.

In a future update, we hope to resolve issues like this by removing the HTTP call and having the client internally signal the durable extension to schedule orchestrations.

@kashimiz Is it still possible to use the output binding strategy to start new orchestration instances in JavaScript? We had this capability before we had the rich orchestration client, but I don't remember if that functionality still works. If it does, that is one possible workaround to this issue.

**Comment by kashimiz** [comment]
We never removed the output binding functionality, so it should still work. I can confirm this in a bit.

**Comment by kashimiz** [comment]
Confirmed the output binding strategy still works. [Here's the old version of the HttpStart sample](https://github.com/Azure/azure-functions-durable-extension/tree/0b7c3605d0a99d4d7be1197a9dd4aa3d02a9ab56/samples/javascript/HttpStart) that used it for reference. Note that you can also have a second orchestration client as an input binding to make use of the `createCheckStatusResponse` method to return management endpoints from the request.

**Comment by bernitorres** [comment]
@kashimiz Could you give an example on how to do the following with function auth?

> Note that you can also have a second orchestration client as an input binding to make use of the createCheckStatusResponse method to return management endpoints from the request.

**Comment by kashimiz** [comment]
Your function.json would look something like this:

```json
{
    "bindings": [
      {
        "authLevel": "function",
        "name": "req",
        "type": "httpTrigger",
        "direction": "in",
        "route": "orchestrators/{functionName}",
        "methods": ["post"]
      },
      {
        "name": "$return",
        "type": "http",
        "direction": "out"
      },
      {
        "name": "client",
        "type": "orchestrationClient",
        "direction": "in"
      },
      {
        "name": "starter",
        "type": "orchestrationClient",
        "direction": "out"
      }
    ],
    "disabled": false
  }
```

and your index.js would look something like this:

```js
const uuidv1 = require("uuid/v1");

module.exports = async function (context, req) {
    const id = uuidv1();
    const client = df.getClient(context);

    let startArgs = [{
        FunctionName: req.params.functionName,
        Input: req.body,
        InstanceId: id
    }];

    context.bindings.starter = startArgs;

    return client.createCheckStatusResponse(context.bindingData.req, id);
};
```

**Comment by CastleArg** [comment]
I'm having this issue even when temporarily setting all functions to anonymous in function.json.
Everything works fine locally.  Is there a  repo for javascript durable functions anywhere that actually runs when deployed to azure?

**Comment by deepbass** [comment]
Hi,

This has just bitten me badly. I'll use the workaround, but seeing that this has been known about since March is there any timeline on a fix?

**Comment by anthonychu** [comment]
We're currently investigating a new way to invoke methods on the host that doesn't require going through the frontend which should address this problem as well. See https://github.com/Azure/azure-functions-durable-js/issues/89
