### ISSUE TITLE
context.df.setCustomStatus sometimes not working in 1.7.1

### ISSUE THREAD

**Issue by deman4ik** [Azure/azure-functions-durable-js#64]
**Describe the bug**
setCustomStatus sometimes doesn't set custom status

**Investigative information**

- Durable Functions extension version: 1.7.1
- Function App version (1.0 or 2.0): 2.0
- Programming language used: JS
- durable-functions npm module version: 1.1.4

**To Reproduce**
I need singleton orchestrator to process external events strictly one by one.
So I use one specific instanceId to start and send events to orchestrator.
Orchestrator receives events with waitForExternalEvent and executes continueAsNew after every processed event.
But because of this #57 bug I can't use 1.8.0 extension version with feature to store external events in memory queue, so to know when I can send external events I use custom status.
I set custom status to "ready" when orchestrator is waiting to external event, and then set custom status to "busy" when orchestrator is processing and can't get new external event.
In my orchestrator clients functions (which are called by Event Grid) I check this custom status and if status is "ready" I send an event to orchestrator and when it is "busy" just store this event to storage table.
When orchestrator starts new invocation it checks storage table for new events, if there are any events in table, orchestrator set status to "busy" and processes all request from table one by one on every new invocation. If there are no events in table, orchestrator sets custom
status to "ready" and waiting for new external event.
This solution is a bit tricky but works.
But sometimes I have a problem when orchestrator can wait to new external event - **setting custom status to "ready" not working**, so orchestrator stuck in custom status "busy" and orchestration clients can't send any events to it (because of my check).
But it seems that orchestrator is waiting for external event at that moment, just custom status not updated.
So now I must manually change custom status to "ready" in HubInstances table to continue work.

Simplified version of my orchestrator function looks like this:
```
df.orchestrator(function*(context) {
  // current state
  let state = context.df.getInput();
  // next event to process
  let nextAction = null;

   // loads new event from azure table storage
   nextAction = yield context.df.callActivity('loadAction', state);

    // if there is no events in table storage
    if (!nextEvent) {
      // set custom status to 'ready'
      context.df.setCustomStatus('ready');
      // wait for new external event
      nextAction = yield context.df.waitForExternalEvent('newEvent');
    }
    // got new event from table storage or orchestration client 
    // set custom status to 'busy'
    context.df.setCustomStatus('busy');

   // processing new event...
   state = yield context.df.callActivity('processEvent', {state, nextAction});
   // restart orchestrator with new state
   yield context.df.continueAsNew(state);
   return state;
});
```

And simplified version of orchestration client function:
```
async function orchClient(context, instanceId, event) {
  const client = df.getClient(context);
  const status = await client.getStatus(instanceId);
    // If orchestrator is running
     if (status && status.runtimeStatus === "Running") {
         // if orchestrator is waiting for new external event
          if (status.customStatus === 'ready) {
                 // send event directly to orchestrator
                  await client.raiseEvent(instanceId, 'newEvent', event);
                } else {
                // or save event to table storage
                  await saveEventToTableStorage({
                    PartitionKey: instanceId,
                    RowKey: event.id,
                    ...event
                  });
                }
     }
}
```

I have 2 csv exports from HubHistory tables with different examples and can send it to email.

Also I would like to ask for advice - is there a better way to implement singleton orchestrator to process events strictly one by one? Maybe it would be simpler just to use some external queue or service bus?

**Comment by kashimiz** [comment]
Thanks for reporting this, @deman4ik. I'd like to take a look at those history table files; could you send them to katy.shimizu@microsoft.com?

Regarding advice, if what you're aiming for is to process events one by one, in order, you probably don't need Durable Functions solely for that. Have you looked at Event Hubs? They can deliver in-order messages in batches or one-by-one.
