### ISSUE TITLE
NPM module still targets depreciated dependencies

### ISSUE THREAD

**Issue by antempus** [Azure/azure-functions-durable-js#67]
npm module built from this repo still has a dependency on [azure-functions-typescript](https://github.com/christopheranderson/azure-functions-typescript.git), but the repo points to 
[@azure/functions](https://www.npmjs.com/package/@azure/functions).

Can cause problems with build systems that don't have `git` on the `$PATH`
EX:
```
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t ssh://git@github.com/christopheranderson/azure-functions-typescript.git
npm ERR! 
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR! 
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.
```

**Comment by kashimiz** [comment]
Thanks for flagging this, @antempus. We'll update this as part of the upcoming 1.1.5 release.
