### ISSUE TITLE
Question: In fan-out/fan-in scenario what happens when one activity fails?

### ISSUE THREAD

**Issue by bernitorres** [Azure/azure-functions-durable-js#82]
**Question**
I have a fan-out/fan-in scenario which queues 100 activities to be executed. Could you explain what happens when activity #90 fails with an exception? Do I get the results for all 100 activities, with the exception being the result of one activity, or does it throw and only the failure is returned?

```
let results;
for (const container of containers) {
        tasks.push(
            context.df.callActivityWithRetry('a_transformContainer', retryOptions, input),
        );
    }
try {
        results = yield context.df.Task.all(tasks);
} catch (error) {
        //do something with error
}
```

Does results contain 99 results and one exception message? Or is the one failure caught in the try/catch block?

**Investigative information**

- Durable Functions extension version: 1.7.0
- Function App version (1.0 or 2.0): 2.0
- Programming language used: typescript

***If JavaScript***

- durable-functions npm module version: 1.1.4

**Comment by kashimiz** [comment]
Update: the fix for issue #66 has gone out in the 1.2.2 release, and should now work as detailed in [this post](https://github.com/Azure/azure-functions-durable-js/issues/66#issuecomment-484984188).
