### ISSUE TITLE
context.df.getInput() always returning null in orchestrator

### ISSUE THREAD

**Issue by hanvyj** [Azure/azure-functions-durable-js#83]
I've previously triggered orchestrators using the following:
```
module.exports = async function(context, input) {
  const instanceId = uuid();

  context.log.warn(`Starting Orchestrator.`, input);
  const startArgs = [
    {
      FunctionName: "Orchestrator",
      Input: input,
      InstanceId: instanceId
    }
  ];

  context.bindings.starter = startArgs;
}
```
With the binding:
```
    {
      "name": "starter",
      "type": "orchestrationClient",
      "direction": "out"
    }
```
However, I've changed it to use the client functionality:

```
module.exports = async function(context, input) {
  const client = df.getClient(context);

  // Replace the axios instance with one that supports "no proxy"
  client.axiosInstance = axios.create();

  context.log.warn(`Starting Orchestrator.`, input);
  const instanceId = await client.startNew("Orchestrator", undefined, input);
}
```
With the binding:
```
    {
      "name": "starter",
      "type": "orchestrationClient",
      "direction": "in"
    }
```
I've managed to get it triggering, however the orchestrator always receives `null` as an input.

I'm testing this with a super simple orchestrator:
```
module.exports = df.orchestrator(function*(context) {
  const input = context.df.getInput();
  context.log.warn("Input", input);
  return [];
});
```

I get always get `Input null` with using the client. The storage tables show `null` for the input for these functions, so the problem must be in the client. I shoved a console log in the client code:

```
         console.log("Sending input", JSON.stringify(input));
        const response = yield this.axiosInstance.post(
          requestUrl,
          JSON.stringify(input)
        );
```

And it's logging data.

**Comment by kashimiz** [comment]
Hi @hanvyj, thank you for reporting this issue and my apologies for the delayed response. Can you provide the following information to help me investigate?

- Durable Functions extension version:
- durable-functions npm module version:
- Language (JavaScript/TypeScript) and version:
- Node.js version:
