### ISSUE TITLE
Durable Function NPM package not backwards compatible

### ISSUE THREAD

**Issue by cliffkoh** [Azure/azure-functions-durable-js#84]
I upgraded the NPM package from 1.1.4 to 1.2.1, and the runtime from 1.7.1 to 1.8.1.

Unfortunately, this upgrade is not backwards compatible and breaks existing orchestrations that are in progress :(

```
Exception while executing function: Functions.Orchestrator Orchestrator function 'orchestrator' failed: One or more errors occurred. (Result: Failure
Exception: TypeError: Cannot read property 'Timestamp' of undefined
```

This exception is specifically thrown at https://github.com/Azure/azure-functions-durable-js/blob/589761b5063fddb2952f3fa32a0848c6056554ba/src/orchestrator.ts#L115

As far as I can tell, new orchestrations started after that is fine. 

Should these upgrades not be safe for existing orchestrations in-progress? If not, that poses a real blocker for ever upgrading the runtime/NPM package...

**Comment by kashimiz** [comment]
Hi @cliffkoh,

A cursory inspection doesn't reveal why that particular error is cropping up in your existing orchestrations, but I suspect it has something to do with a breaking change that was made to the DurableTask.Core repo between those releases.

We do occasionally release updates to the Durable Functions extension and npm package that contain breaking changes, which we call out in our release notes, but we may have misstepped with our semver here. The jump from 1.7.1 to 1.8.0 contained some big changes, including some that were breaking for this repo, and the durable-functions releases had to move to accommodate. I'm sorry you got bit by this.

In general, this repo's release numbers follow what azure/azure-functions-durable-extension does, which is a little different from strict semver; if a minor release number increases, that means there's Changes Afoot and it's good to cautious when upgrading. Major release number increases are rare and indicate a significant shift that isn't backwards-compatible. Patch releases should be OK.

Our documentation article about [versioning](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-versioning) is worth a read; although it approaches the topic from the customer code side, the [mitigation strategies](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-versioning#mitigation-strategies) apply to any change that affects how the history events for an in-flight orchestration are handled.
