### ISSUE TITLE
client.startNew function throws intermittent error when function app runs in Azure

### ISSUE THREAD

**Issue by harshithkashyap** [Azure/azure-functions-durable-js#90]
**Describe the bug**
When calling the orchestration function in Azure using `client.startNew(...)` method, durable functions throws unknown error with no error message in the exception. From the stack trace and error message in App Insights, the following message is logged.

`Exception while executing function: Functions.CL_skill-execution-approval-change <--- Result: Failure Exception: Error Stack: Error at DurableOrchestrationClient.<anonymous> (D:\home\site\wwwroot\node_modules\durable-functions\lib\src\durableorchestrationclient.js:284:43) at Generator.next (<anonymous>) at fulfilled (D:\home\site\wwwroot\node_modules\durable-functions\lib\src\durableorchestrationclient.js:4:58) at process._tickCallback (internal/process/next_tick.js:68:7)`

**Investigative information**

- Durable Functions extension version: 1.8.2
- durable-functions npm module version: 1.2.2
- Language (JavaScript/TypeScript) and version: Typescript and 3.5.1
- Node.js version: 10.15.2

***If deployed to Azure App Service***

- Timeframe issue observed:
- Invocation ID: 49cc1fa2-3a28-471b-afae-910a69e2797a
- Region: East US
- Timestamp: 2019-06-10 18:00:16.099
- Orchestration instance ID(s): Instance ID isn't generated and throws error when starting the instance.

> If you don't want to share your Function App name or Functions names on GitHub, please be sure to provide your Invocation ID, Timestamp, and Region - we can use this to look up your Function App/Function. Provide an invocation id per Function. See the [Functions Host wiki](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately) for more details.

**To Reproduce**

Unfortunately, I have not been able to reproduce this issue locally and this is occurring only in the deployed azure function app.

> While not required, providing your orchestrator's source code in anonymized form is often very helpful when investigating unexpected orchestrator behavior.

```typescript
import { AzureFunction, Context } from '@azure/functions';
import { getClient } from 'durable-functions';
import { SkillExecutionQueueMessage } from '../interfaces/skills';

const queueTrigger: AzureFunction = async (context: Context, queueMessage: SkillExecutionQueueMessage) => {
    try {
        const client = getClient(context);
        const instanceId = await client.startNew('OC_skill-approval-change', undefined, queueMessage);

        context.log(`Started Skill approval change orchestration with ID = '${instanceId}'.`);
    } catch (error) {
        return Promise.reject(error);
    }
};

export default queueTrigger;
```

**Expected behavior**
The error message should be descriptive and should be consistent in all scenarios.

**Actual behavior**
The function app throws exceptions when calling `startNew()` method in 4 out of 5 cases when all the parameters remain same. Its unclear and the exception produces no error message about the actual issue.

**Screenshots**

**Known workarounds**
Provide a description of any known workarounds you used.

**Additional context**

- Development environment (ex. Visual Studio) VS Code
- Links to source
- Additional bindings used
- Function invocation IDs:  `49cc1fa2-3a28-471b-afae-910a69e2797a`, `ea223e31-9a2a-432c-b66b-9522ec834c2f`, `d43df121-a503-44db-abbf-0f65ff373b21
`

**Comment by Rapol** [comment]
Im having the same problem, I followed the tutorial to create durable functions in https://docs.microsoft.com/en-us/azure/azure-functions/durable/quickstart-js-vscode
Im able to run it locally but when i deploy I get the same error as OP.

Investigative information
- durable-functions: 1.3.0
- func: 2.7.1724
- Node.js: 10.15.2
- Premium Service Plan running Linux
- Function Runtime version: 2.0.12808.0 (~2)
- Region East US

HTTP Trigger function that kicks up orchestrators
```
/*
 * HTTP trigger that starts can start any orchestrator by passing a function name as a url parameter
 */

const df = require("durable-functions");

module.exports = async function (context, req) {
    const client = df.getClient(context);
    const instanceId = await client.startNew(req.params.functionName, undefined, req.body);

    context.log(`Started orchestration with ID = '${instanceId}'.`);

    return client.createCheckStatusResponse(context.bindingData.req, instanceId);
};
```

Invocation Id 4e65429c-7191-401a-b5fb-ff289f3309c2 (2019-10-22 20:32:32.147)
Error:
```
Result: Failure
Exception: Error
Stack: Error
    at DurableOrchestrationClient.<anonymous> (/home/site/wwwroot/node_modules/durable-functions/lib/src/durableorchestrationclient.js:331:43)
    at Generator.next (<anonymous>)
    at fulfilled (/home/site/wwwroot/node_modules/durable-functions/lib/src/durableorchestrationclient.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by Rapol** [comment]
I originally deployed it using azure-function-tools (func). Decided to try a deployment via the VSCode Azure plugin. I then when back to deploy it via func and it still works. So not sure what happened.

I just started using azure 3 weeks ago and I have run into multiple weird issues that dont have any explanation, it just gets fixed magically or via redeployments. I also have a storage account which is stuck in "Creating..." for 5 days and have no way of stopping it or deleting it. AFIK, there is no way to contact support unless I buy a support plan..

**Comment by st3v3nhunt** [comment]
I've experienced this issue. I fixed it by making sure the name of the function directory and the string used to identify the function when calling `client.startNew(<function-name>, ...)` were exactly the same - it is case sensitive, which is what caught me out.

Everything was running OK locally (I was using all lower case function names). However, when I deployed the app to Azure the orchestrator function had somehow become renamed with an upper case first letter i.e. from `orchestrator` to `Orchestrator`. I thought it was strange but ignored it until the app wasn't working. The exception was pretty much the same as above i.e. originating from the call to `client.startNew(...)`. After some digging and finding this issue I recognised the problem and renamed the function directory to avoid casing issues.

The easiest way to reproduce the issue is by changing the call to `client.startNew(...)` so it tries to start a function that doesn't exist. The error message is a little lacking in useful information.

Hopefully this will help somebody else.

**Comment by boreys** [comment]
This code will repro the hidden bug:

module.exports = async function (context, req) {
    const client = df.getClient(context);
   
    const instanceId = await client.startNew(req.params.functionName, undefined, "some string");

    context.log(`Started orchestration with ID = '${instanceId}'.`);

    return client.createCheckStatusResponse(context.bindingData.req, instanceId);
};
