### ISSUE TITLE
Durable Entities design work

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-js#92]
Durable Entities currently supports .NET but we want to also have support for JavaScript. Some out-of-proc work was done to enable this in [this PR]() (which will be available in the **beta1** release), but it has not yet been validated. This work item tracks doing the design investigation for adding support for Durable Entities in TypeScript/JavaScript.

The intent of the design work is to help identify the programming model as well as any concrete work items that need to be done to release the feature. The core things the design should cover:

- [x] **Core programming model** - i.e. what does the JavaScript shim look like, what are the APIs, etc.
- [x] **Wire protocol** - there is an assumed protocol in the current extension implementation, but we need to document it and make sure that it's actually reasonable.
- [x] **Samples** - they don't have to be functional but should at least illustrate the desired programming model, which can be discussed and debated.

Some base assumptions:

* The existing _durable-functions_ npm package contains the APIs needed for durable entities.
* TypeScript interfaces will exist, just like they do for orchestrations
* The new entity trigger would require the 2.0 version of the Durable extension.

**Comment by fabiocav** [comment]
Moving this to sprint 54. 
@kashimiz can provide an update on progress, but a good portion of this has been completed and she is moving into the implementation phase.

**Comment by fabiocav** [comment]
Let's break this issue down so we can properly track the work in the upcoming sprint(s)

**Comment by kashimiz** [comment]
Yes; JS support extends to TypeScript. Please take a look at Azure Functions' [documentation on writing TypeScript functions](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#typescript) for more information and guidance.

**Comment by andreujuanc** [comment]
@kashimiz there is no types ATM for durable, at least I haven't found them. The fact that azure functions comes with types does not mean that this project gets the types it needs.

**Comment by jschumann** [comment]
> * **Samples** - they don't have to be functional but should at least illustrate the desired programming model, which can be discussed and debated.

When I browse the samples folder, I see one sample for a Durable Entity: the CounterEntity. There are, to me, no other obvious samples of Durable Entities. I'm sorry if I've missed others. 

Can we have a sample of Class-based syntax for a Durable Entity (suitable for use from TypeScript)?

**Comment by ConnorMcMahon** [comment]
@jschumann, there is currently no class based syntax for Durable Entities on JS. I will open a new issue to track programming model improvements.

**Comment by jschumann** [comment]
@ConnorMcMahon Many thanks!
