### ISSUE TITLE
Combination of callActivityWithRetry and Task.all showing unexpected behaviour

### ISSUE THREAD

**Issue by farzanDE** [Azure/azure-functions-durable-js#99]
**Describe the bug**
A combination of `context.df.callActivityWithRetry` and `context.df.Task.all` results in strange behaviour. Here is a simplified version of my code:

    let results;
    for (let i=0; i < batch.length; i++) {
        tasks.push(
            context.df.callActivityWithRetry('functionUploadData', retryOptions, batch[i])
        );
    }
    try {
        results = yield context.df.Task.all(tasks);
    } catch (error) {
        context.log(error);
    }
    let output = yield context.df.callActivityWithRetry('functionWriteToBlob', retryOptions, results);
    context.log(output);

The code runs as expected until the line 
`let output = yield context.df.callActivityWithRetry('functionWriteToBlob', retryOptions, results);`
I'm able to debug and see that the data in `results` is correct at this point. However, `functionWriteToBlob` never runs (it never even enters the function). Instead another instance of `functionUploadData` is executed following which the orchestration status changes to "Completed". The line `context.log(output)` is never reached.

Looking at the history table, I can see that the orchestrator schedules `functionUploadData` when it should be scheduling `functionWriteToBlob`. The input parameters are the same as a previous call to the function.

If I replace `callActivityWithRetry` for `functionUploadData` with `callActivity`, the orchestrator then behaves properly. Since there are no retries, an exception is usually thrown which is captured by the catch block, but the subsequent call to `functionWriteToBlob` executes properly. Also note that in the original version of the code, when an exception is thrown (if the max retry attempts are exceeded), the problem still occurs i.e. `functionWriteToBlob` in not executed. 

**Investigative information**

- Durable Functions extension version: 1.8.2
- durable-functions npm module version: 1.2.2
- Language: Javascript
- Node.js version: 8.12.0

Only tested this locally so far so not sure if the behaviour will be same on Azure. Locally, I've tried clearing everything in the TaskHub before testing to make sure it is not some old remnant of a function instance that is being picked up.

**To Reproduce**
Try implementing the code sample above

Any guidance will be appreciated.

**Comment by KieranDaviesV** [comment]
I had a similar issue as above, the way i got around it is by having the for loop inside its own Orchestrator. Have that Orchestrator return the results you want and give them to your other activity, hopefully this will help you. I Know you posted this a long time ago

**Comment by farzanDE** [comment]
Thanks for the suggested workaround. I can try that when faced with something similar in the future. For this case, I got around it by only using `callActivity` along with some custom retry logic in the catch block (essentially a custom implementation of what `callActivityWithRetry` should be doing). 

Surely this is a bug in `callActivityWithRetry`?

**Comment by KieranDaviesV** [comment]
Potentially, It might be a bug with the the Task all? as im having issues with running stuff after that

**Comment by ConnorMcMahon** [comment]
@farzanDE or @KieranDaviesV 

I have tested this on 1.3.3, and it looks like this behavior is no longer present. We have recently made some rather major refactors to `Task.all()`, which appear to have fixed the issue.

**Comment by ConnorMcMahon** [comment]
Fixed in 1.4.2.
